{
  "hash": "b768141fe46bfd7e1799f6b0f61f88d5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 07. Multiple Linear Regression. Practice.\"\neditor: source\nformat: \n  revealjs:\n    preview-links: true\neditor_options: \n  chunk_output_type: console\n---\n\n# Causal interpretation of the MLR\n\n## Multiple Regression Controls for the factors that matter...\n\n::: fragment\n-   These are only the factors that are included in the model.\n:::\n\n::: fragment\n::: {.callout-note appearance=\"simple\"}\n### All other factors that are not included in the MLR are assumed to remain constant!\n\n-   External Ceteris Paribus is assumed.\n:::\n:::\n\n::: fragment\nViolation of the Ceteris Paribus causes Bias.\n:::\n\n## Regression assumptions\n\n> They ensure that linear regression estimates obtained using the OLS method are **unbiased** and **efficient**.\n\n-   [**OLS is unbiased: Assumptions 1 to 4 are satisfied**]{style=\"color: red;\"}\n\n    (1) Linearity\n    (2) Random Sampling\n    (3) No Collinearity\n    (4) No Endogeneity\n    \n-   [**OLS is unbiased and efficient or Best Linear Unbiased Estimator (BLUE)**]{style=\"color: blue;\"}\n\n    (5) Homoscedasticity (No Autocorrelation)\n    \n-   [**OLS is a Classical linear model (CLM). Assumptions 1 to 6 are satisfied**]{style=\"color: green;\"}\n\n    (6) Error Terms Normality\n\n# Example 1. Hedonic Land prices model\n\n---\neditor: source\nformat: \n  revealjs:\n    preview-links: true\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n## 1. Problem setting\n\nWe would like to assess the effect of the \"Conservation Reserve Program\" (CPR) on agricultural land prices.\n\n::: incremental\nConservation Reserve Program\n\n-   is a subsidy\n-   obligates farms NOT TO GROW ANY CROPS on the enrolled land\n-   pays monetary compensation in exchange;\n:::\n\n::: fragment\nThis is a riskless income, so it may increase the land price.\n\n-   However, if the land is productive, such set-aside measures may reduce farmland prices.\n:::\n\n\n::: {.cell}\n\n:::\n\n\n## 2. Regression model formulation {.smaller}\n\nThe hedonic price model [@palmquist1989] is an econometric approach to quantifying monetary values of differentiated characteristics of goods or services, which are subjects of economic exchange.\n\nThe theory of the hedonic price model allows us to estimate the price as a function of all characteristics of a good. Available variables in our data [@taff2007compensated] are:\n\n::: fragment\n::: columns\n::: {.column width=\"50%\"}\n-   `acrePrice` - sale price in dollars per acre;\n-   `crpPct` - the percentage of the farm area enrolled in CRP;\n-   `acres` - the size of the farm in acres;\n-   `region` - a region in the state of Minnesota;\n:::\n\n::: {.column width=\"50%\"}\n-   `tillable` - the percentage of the farm that is rated arable by the assessor;\n-   `productivity` - average agronomic productivity scaled from 1 to 100, with larger numbers for more productive land;\n:::\n:::\n\n::: fragment\nEQ: **Write down a regression equation that could help answering the main research question.**\n:::\n\n::: fragment\n$$\n\\begin{aligned}\n\\operatorname{acrePrice} &= \\alpha + \\beta_{1}(\\operatorname{crpPct}) + \\beta_{2}(\\operatorname{acres})\\ + \\\\\n&\\quad \\beta_{3}(\\operatorname{region}_{\\operatorname{West\\ Central}}) + \\beta_{4}(\\operatorname{region}_{\\operatorname{Central}}) + \\beta_{5}(\\operatorname{region}_{\\operatorname{South\\ West}})\\ + \\\\\n&\\quad \\beta_{6}(\\operatorname{region}_{\\operatorname{South\\ Central}}) + \\beta_{7}(\\operatorname{region}_{\\operatorname{South\\ East}}) + \\beta_{8}(\\operatorname{tillable})\\ + \\\\\n&\\quad \\beta_{9}(\\operatorname{productivity}) + \\epsilon\n\\end{aligned}\n$$\n:::\n\n::: fragment\nEQ: **Formulate the ex-ante hypothesis about the sign and magnitude of the coefficient \"\\_\\_\\_\\_\\_\\_\". In 1-2 sentences, explain why (based on what theory, common sense) you make this hypothesis.**\n:::\n:::\n\n## 3 Exploratory data analysis {.smaller}\n\n### 3.1 The data\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| acrePrice| acres|region        | tillable| crpPct| productivity|\n|---------:|-----:|:-------------|--------:|------:|------------:|\n|      2933|   303|West Central  |       75|     23|           53|\n|      2283|   265|West Central  |       75|      3|           52|\n|      2150|    40|South West    |       90|     20|           72|\n|      2432|   110|West Central  |       60|     50|           48|\n|      1494|    77|Northwest     |       90|     93|           45|\n|      2495|   192|West Central  |       97|     17|           64|\n|      4086|   220|West Central  |       95|      3|           65|\n|      1400|    78|West Central  |       56|     13|           43|\n|      2092|    75|West Central  |      100|     13|           69|\n|      1852|    58|West Central  |       93|     34|           43|\n|      1458|   120|Northwest     |       88|     69|           34|\n|      2600|    77|West Central  |       96|      4|           57|\n|      1051|    97|South West    |       82|     73|           50|\n|      2544|   117|South West    |       98|      3|           59|\n|      2013|    75|South Central |       96|      5|           42|\n\n\n:::\n:::\n\n\n## 3.2 Summary statistics {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_qqnluti52ck53133can0(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_qqnluti52ck53133can0\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_qqnluti52ck53133can0(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_qqnluti52ck53133can0\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '5', j: 5 }, { i: '5', j: 1 }, { i: '5', j: 2 }, { i: '5', j: 3 }, { i: '5', j: 6 }, { i: '5', j: 4 }, { i: '5', j: 7 },  ], css_id: 'tinytable_css_j6hackilsvj2ilvgco78',}, \n          { positions: [ { i: '1', j: 1 }, { i: '3', j: 1 }, { i: '3', j: 2 }, { i: '2', j: 1 }, { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '4', j: 1 }, { i: '1', j: 6 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '4', j: 4 }, { i: '4', j: 2 }, { i: '1', j: 7 }, { i: '1', j: 5 }, { i: '2', j: 5 }, { i: '3', j: 5 }, { i: '4', j: 5 }, { i: '3', j: 6 }, { i: '4', j: 6 }, { i: '3', j: 7 }, { i: '2', j: 6 }, { i: '2', j: 7 }, { i: '4', j: 7 },  ], css_id: 'tinytable_css_1xna0fubvfp36vm1xpr5',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 4 }, { i: '0', j: 2 }, { i: '0', j: 5 }, { i: '0', j: 6 }, { i: '0', j: 7 }, { i: '0', j: 3 },  ], css_id: 'tinytable_css_wzio67l0dc4n0r33ks0w',}, \n          { positions: [ { i: '5', j: 0 },  ], css_id: 'tinytable_css_lpzblnnrbgfrp6z73f67',}, \n          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 }, { i: '3', j: 0 }, { i: '4', j: 0 },  ], css_id: 'tinytable_css_6rnwyfnlg56rt3l55p3r',}, \n          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_bnnenrjk959g2hq9vti9',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_qqnluti52ck53133can0(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_j6hackilsvj2ilvgco78, .table th.tinytable_css_j6hackilsvj2ilvgco78 { text-align: right; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_1xna0fubvfp36vm1xpr5, .table th.tinytable_css_1xna0fubvfp36vm1xpr5 { text-align: right; }\n      .table td.tinytable_css_wzio67l0dc4n0r33ks0w, .table th.tinytable_css_wzio67l0dc4n0r33ks0w { text-align: right; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_lpzblnnrbgfrp6z73f67, .table th.tinytable_css_lpzblnnrbgfrp6z73f67 { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_6rnwyfnlg56rt3l55p3r, .table th.tinytable_css_6rnwyfnlg56rt3l55p3r { text-align: left; }\n      .table td.tinytable_css_bnnenrjk959g2hq9vti9, .table th.tinytable_css_bnnenrjk959g2hq9vti9 { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_qqnluti52ck53133can0\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">N</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Mean</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">SD</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Min</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">Median</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">Max</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"7\">Histogram</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">acrePrice</td>\n                  <td data-row=\"1\" data-col=\"1\">8787</td>\n                  <td data-row=\"1\" data-col=\"2\">3044.24</td>\n                  <td data-row=\"1\" data-col=\"3\">1553.36</td>\n                  <td data-row=\"1\" data-col=\"4\">173.00</td>\n                  <td data-row=\"1\" data-col=\"5\">2800.00</td>\n                  <td data-row=\"1\" data-col=\"6\">14379.00</td>\n                  <td data-row=\"1\" data-col=\"7\">▃▇▄▂</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">acres</td>\n                  <td data-row=\"2\" data-col=\"1\">8787</td>\n                  <td data-row=\"2\" data-col=\"2\">114.79</td>\n                  <td data-row=\"2\" data-col=\"3\">88.15</td>\n                  <td data-row=\"2\" data-col=\"4\">1.00</td>\n                  <td data-row=\"2\" data-col=\"5\">80.00</td>\n                  <td data-row=\"2\" data-col=\"6\">1365.00</td>\n                  <td data-row=\"2\" data-col=\"7\">▇▃</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">tillable</td>\n                  <td data-row=\"3\" data-col=\"1\">8787</td>\n                  <td data-row=\"3\" data-col=\"2\">88.19</td>\n                  <td data-row=\"3\" data-col=\"3\">15.82</td>\n                  <td data-row=\"3\" data-col=\"4\">5.00</td>\n                  <td data-row=\"3\" data-col=\"5\">94.00</td>\n                  <td data-row=\"3\" data-col=\"6\">100.00</td>\n                  <td data-row=\"3\" data-col=\"7\">▁▂▇</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">crpPct</td>\n                  <td data-row=\"4\" data-col=\"1\">8787</td>\n                  <td data-row=\"4\" data-col=\"2\">2.93</td>\n                  <td data-row=\"4\" data-col=\"3\">13.63</td>\n                  <td data-row=\"4\" data-col=\"4\">0.00</td>\n                  <td data-row=\"4\" data-col=\"5\">0.00</td>\n                  <td data-row=\"4\" data-col=\"6\">100.00</td>\n                  <td data-row=\"4\" data-col=\"7\">▇</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"0\">productivity</td>\n                  <td data-row=\"5\" data-col=\"1\">8787</td>\n                  <td data-row=\"5\" data-col=\"2\">66.74</td>\n                  <td data-row=\"5\" data-col=\"3\">13.48</td>\n                  <td data-row=\"5\" data-col=\"4\">1.00</td>\n                  <td data-row=\"5\" data-col=\"5\">68.00</td>\n                  <td data-row=\"5\" data-col=\"6\">99.00</td>\n                  <td data-row=\"5\" data-col=\"7\">▁▂▃▇▇▃▁</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_adh8cc04nfkqhgj1rzmq(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_adh8cc04nfkqhgj1rzmq\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_adh8cc04nfkqhgj1rzmq(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_adh8cc04nfkqhgj1rzmq\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '7', j: 1 }, { i: '7', j: 2 },  ], css_id: 'tinytable_css_gbdmmnhgvkjf2lk21mvx',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '3', j: 2 }, { i: '4', j: 1 }, { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 },  ], css_id: 'tinytable_css_1e0na6rs5a7vilu3df86',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 },  ], css_id: 'tinytable_css_c7n2rz6whj2oao5hhszu',}, \n          { positions: [ { i: '7', j: 0 },  ], css_id: 'tinytable_css_s81aw6adw7yli3pvusg1',}, \n          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 }, { i: '3', j: 0 }, { i: '4', j: 0 }, { i: '5', j: 0 }, { i: '6', j: 0 },  ], css_id: 'tinytable_css_10k78vgauky46gwfehic',}, \n          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_g2xx9wsso3jxg6t0rndw',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_adh8cc04nfkqhgj1rzmq(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_gbdmmnhgvkjf2lk21mvx, .table th.tinytable_css_gbdmmnhgvkjf2lk21mvx { text-align: right; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_1e0na6rs5a7vilu3df86, .table th.tinytable_css_1e0na6rs5a7vilu3df86 { text-align: right; }\n      .table td.tinytable_css_c7n2rz6whj2oao5hhszu, .table th.tinytable_css_c7n2rz6whj2oao5hhszu { text-align: right; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_s81aw6adw7yli3pvusg1, .table th.tinytable_css_s81aw6adw7yli3pvusg1 { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_10k78vgauky46gwfehic, .table th.tinytable_css_10k78vgauky46gwfehic { text-align: left; }\n      .table td.tinytable_css_g2xx9wsso3jxg6t0rndw, .table th.tinytable_css_g2xx9wsso3jxg6t0rndw { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_adh8cc04nfkqhgj1rzmq\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\">region</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">N</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">%</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">Northwest</td>\n                  <td data-row=\"1\" data-col=\"1\">788</td>\n                  <td data-row=\"1\" data-col=\"2\">9.0</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">West Central</td>\n                  <td data-row=\"2\" data-col=\"1\">1747</td>\n                  <td data-row=\"2\" data-col=\"2\">19.9</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">Central</td>\n                  <td data-row=\"3\" data-col=\"1\">1058</td>\n                  <td data-row=\"3\" data-col=\"2\">12.0</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">South West</td>\n                  <td data-row=\"4\" data-col=\"1\">2438</td>\n                  <td data-row=\"4\" data-col=\"2\">27.7</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"0\">South Central</td>\n                  <td data-row=\"5\" data-col=\"1\">1983</td>\n                  <td data-row=\"5\" data-col=\"2\">22.6</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"0\">South East</td>\n                  <td data-row=\"6\" data-col=\"1\">773</td>\n                  <td data-row=\"6\" data-col=\"2\">8.8</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"0\"></td>\n                  <td data-row=\"7\" data-col=\"1\">8787</td>\n                  <td data-row=\"7\" data-col=\"2\">100.0</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n## 3.3 Regional differences {.smaller}\n\n::: columns\n::: {.column width=\"75%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](mk68-07-slides_files/figure-revealjs/unnamed-chunk-6-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"25%\"}\n-   What kind of plot is this?\n-   **What (if any) transformation of the Y axis is used on the plot?**\n-   What can we conclude about the land prices by region?\n-   EQ: **What are the possible causes of price differences between the regions?**\n-   EQ: **Does the region cause land prices to be different?**\n:::\n:::\n\n## 3.4 Distributions\n\n::: columns\n::: {.column width=\"75%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](mk68-07-slides_files/figure-revealjs/unnamed-chunk-7-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"25%\"}\n-   What kind of plot is this?\n-   What does it show?\n-   **What (if any) transformation of the X axis is used on the plot?**\n-   What differences and similarities does it manifest?\n:::\n:::\n\n## 3.5 Scatter plots {.smaller}\n\n::: columns\n::: {.column width=\"75%\"}\n::: r-stack\n\n::: {.cell}\n::: {.cell-output-display}\n![](mk68-07-slides_files/figure-revealjs/unnamed-chunk-8-1.png){width=100%}\n:::\n:::\n\n\n::: fragment\n\n::: {.cell}\n::: {.cell-output-display}\n![](mk68-07-slides_files/figure-revealjs/unnamed-chunk-9-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: fragment\n\n::: {.cell}\n::: {.cell-output-display}\n![](mk68-07-slides_files/figure-revealjs/unnamed-chunk-10-1.png){width=100%}\n:::\n:::\n\n:::\n:::\n:::\n\n::: {.column width=\"25%\"}\n-   EQ: **What kind of relationship exists between `acrePrices` (land price per acre, USD) and `acres` (plot size in acres) variables?** (Linear/non linear, strong/weak correlation, positive/negative)\n\n-   EQ: same question for any other pair of variables.\n:::\n:::\n\n## 4. Estimating the regression\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"1-3,7-16,18-20\"}\nfit_land_0 <- lm(\n  acrePrice ~ crpPct + acres + region + tillable +  productivity, \n  landprice_dta)\nsummary(fit_land_0)\n# Coefficients:\n#                      Estimate Std. Error t value Pr(>|t|)    \n# (Intercept)           80.2822   102.3493   0.784   0.4328    \n# crpPct                -6.9429     1.0727  -6.473 1.02e-10 ***\n# acres                 -1.2898     0.1650  -7.818 6.00e-15 ***\n# regionWest Central   995.2924    58.0391  17.149  < 2e-16 ***\n# regionCentral       1950.2114    64.5434  30.215  < 2e-16 ***\n# regionSouth West    1291.8278    58.3426  22.142  < 2e-16 ***\n# regionSouth Central 1747.5506    62.5597  27.934  < 2e-16 ***\n# regionSouth East    2040.6768    72.4923  28.150  < 2e-16 ***\n# tillable               2.1123     0.9691   2.180   0.0293 *  \n# productivity          23.6903     1.3300  17.812  < 2e-16 ***\n# \n# Residual standard error: 1332 on 8777 degrees of freedom\n# Multiple R-squared:  0.2654,\tAdjusted R-squared:  0.2647 \n# F-statistic: 352.4 on 9 and 8777 DF,  p-value: < 2.2e-16\n```\n:::\n\n\n## 6. Results interpretation {.smaller}\n\n::: columns\n::: {.column width=\"70%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Parameter              | Coefficient |     SE | t(8777) |      p |\n|:----------------------|:-----------:|:------:|:-------:|:------:|\n|(Intercept)            |       80.28 | 102.35 |    0.78 | 0.433  |\n|crpPct                 |       -6.94 |   1.07 |   -6.47 | < .001 |\n|acres                  |       -1.29 |   0.16 |   -7.82 | < .001 |\n|region (West Central)  |      995.29 |  58.04 |   17.15 | < .001 |\n|region (Central)       |     1950.21 |  64.54 |   30.22 | < .001 |\n|region (South West)    |     1291.83 |  58.34 |   22.14 | < .001 |\n|region (South Central) |     1747.55 |  62.56 |   27.93 | < .001 |\n|region (South East)    |     2040.68 |  72.49 |   28.15 | < .001 |\n|tillable               |        2.11 |   0.97 |    2.18 | 0.029  |\n|productivity           |       23.69 |   1.33 |   17.81 | < .001 |\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\n::: fragment\nNote units of measurement:\n\n`acrePrice` sale price in USD per acre;\n\n`crpPct` is % of all farm acres enrolled under the program (CRP);\n\n`acres` size of the farm in acres;\n\n`region` is the sub-regions in the state of Minnesota;\n\n`tillable` is the percentage of the farm that is rated arable by the assessor;\n\n`productivity` is the average agronomic productivity scaled from 1 to 100, with larger numbers for more productive land.\n:::\n:::\n:::\n\n::: fragment\nEQ: **Write down the full interpretation of and perform a hypothesis testing on each coefficient.**\n:::\n\n## 5. Checking the linearity assumption\n\n::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](mk68-07-slides_files/figure-revealjs/unnamed-chunk-13-1.png){width=100%}\n:::\n:::\n\n\n::: fragment\nIs the relationship between `acrePrice` and `acres` linear?\n:::\n:::\n\n::: {.column width=\"50%\"}\n::: fragment\n\n::: {.cell}\n::: {.cell-output-display}\n![](mk68-07-slides_files/figure-revealjs/unnamed-chunk-14-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: fragment\nIs the linearity assumption satisfied in our regression?\n:::\n:::\n:::\n\n## 4. Regression re-specification {.smaller}\n\n\n::: {.cell}\n\n:::\n\n\nLet us transform `acrePrice` and `acres` variables with the log transformation and estimate the regression again. The old regression is:\n\n$$\n\\begin{aligned}\n\\operatorname{acrePrice} &= \\alpha + \\beta_{1}(\\operatorname{crpPct}) + \\beta_{2}(\\operatorname{acres})\\ + \\\\\n&\\quad \\beta_{3}(\\operatorname{region}_{\\operatorname{West\\ Central}}) + \\beta_{4}(\\operatorname{region}_{\\operatorname{Central}}) + \\beta_{5}(\\operatorname{region}_{\\operatorname{South\\ West}})\\ + \\\\\n&\\quad \\beta_{6}(\\operatorname{region}_{\\operatorname{South\\ Central}}) + \\beta_{7}(\\operatorname{region}_{\\operatorname{South\\ East}}) + \\beta_{8}(\\operatorname{tillable})\\ + \\\\\n&\\quad \\beta_{9}(\\operatorname{productivity}) + \\epsilon\n\\end{aligned}\n$$\n\n::: fragment\n**Write down the new regression equation with the transformations.**\n:::\n\n::: fragment\n$$\n\\begin{aligned}\n\\operatorname{log(acrePrice)} &= \\alpha + \\beta_{1}(\\operatorname{crpPct}) + \\beta_{2}(\\operatorname{\\log(acres)})\\ + \\\\\n&\\quad \\beta_{3}(\\operatorname{region}_{\\operatorname{West\\ Central}}) + \\beta_{4}(\\operatorname{region}_{\\operatorname{Central}}) + \\beta_{5}(\\operatorname{region}_{\\operatorname{South\\ West}})\\ + \\\\\n&\\quad \\beta_{6}(\\operatorname{region}_{\\operatorname{South\\ Central}}) + \\beta_{7}(\\operatorname{region}_{\\operatorname{South\\ East}}) + \\beta_{8}(\\operatorname{tillable})\\ + \\\\\n&\\quad \\beta_{9}(\\operatorname{productivity}) + \\epsilon\n\\end{aligned}\n$$\n:::\n\n## 4.1 Results of the re-specified regression {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_bkbq0g8juxqdhz93hq4e(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_bkbq0g8juxqdhz93hq4e\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_bkbq0g8juxqdhz93hq4e(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_bkbq0g8juxqdhz93hq4e\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '13', j: 1 },  ], css_id: 'tinytable_css_rhskbrmzwmuymesxo3dv',}, \n          { positions: [ { i: '10', j: 1 },  ], css_id: 'tinytable_css_cli8vaac9qrac11vvscn',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 },  ], css_id: 'tinytable_css_tgbhwdxsdp81m75kgan5',}, \n          { positions: [ { i: '0', j: 1 },  ], css_id: 'tinytable_css_alm9coxrl7tr8w6hgfna',}, \n          { positions: [ { i: '13', j: 0 },  ], css_id: 'tinytable_css_mte23vg8l4dpykrcovas',}, \n          { positions: [ { i: '10', j: 0 },  ], css_id: 'tinytable_css_8evwz8fxqeu87evz2grn',}, \n          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 }, { i: '3', j: 0 }, { i: '4', j: 0 }, { i: '5', j: 0 }, { i: '6', j: 0 }, { i: '7', j: 0 }, { i: '8', j: 0 }, { i: '9', j: 0 }, { i: '11', j: 0 }, { i: '12', j: 0 },  ], css_id: 'tinytable_css_sdunbd7eozf5le9vsjrb',}, \n          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_0za94aexo1g4ilku73uy',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_bkbq0g8juxqdhz93hq4e(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_rhskbrmzwmuymesxo3dv, .table th.tinytable_css_rhskbrmzwmuymesxo3dv { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_cli8vaac9qrac11vvscn, .table th.tinytable_css_cli8vaac9qrac11vvscn { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_tgbhwdxsdp81m75kgan5, .table th.tinytable_css_tgbhwdxsdp81m75kgan5 { text-align: center; }\n      .table td.tinytable_css_alm9coxrl7tr8w6hgfna, .table th.tinytable_css_alm9coxrl7tr8w6hgfna { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_mte23vg8l4dpykrcovas, .table th.tinytable_css_mte23vg8l4dpykrcovas { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_8evwz8fxqeu87evz2grn, .table th.tinytable_css_8evwz8fxqeu87evz2grn { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_sdunbd7eozf5le9vsjrb, .table th.tinytable_css_sdunbd7eozf5le9vsjrb { text-align: left; }\n      .table td.tinytable_css_0za94aexo1g4ilku73uy, .table th.tinytable_css_0za94aexo1g4ilku73uy { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_bkbq0g8juxqdhz93hq4e\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">log(acrePrice)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>p-values are: '+' p < 0.1, '\\*' p < 0.05, '\\*\\*' p < 0.01, '\\*\\*\\*' p < 0.001. \n    Standard errors are reported in parentheses</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"1\">6.608 (0.042)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">crpPct</td>\n                  <td data-row=\"2\" data-col=\"1\">-0.003 (0.000)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">log(acres)</td>\n                  <td data-row=\"3\" data-col=\"1\">-0.069 (0.007)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">regionWest Central</td>\n                  <td data-row=\"4\" data-col=\"1\">0.624 (0.018)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"0\">regionCentral</td>\n                  <td data-row=\"5\" data-col=\"1\">0.936 (0.021)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"0\">regionSouth West</td>\n                  <td data-row=\"6\" data-col=\"1\">0.712 (0.019)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"0\">regionSouth Central</td>\n                  <td data-row=\"7\" data-col=\"1\">0.849 (0.020)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"0\">regionSouth East</td>\n                  <td data-row=\"8\" data-col=\"1\">0.939 (0.023)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"0\">tillable</td>\n                  <td data-row=\"9\" data-col=\"1\">0.003 (0.000)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"0\">productivity</td>\n                  <td data-row=\"10\" data-col=\"1\">0.009 (0.000)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"0\">Num.Obs.</td>\n                  <td data-row=\"11\" data-col=\"1\">8787</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"0\">R2</td>\n                  <td data-row=\"12\" data-col=\"1\">0.408</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"0\">R2 Adj.</td>\n                  <td data-row=\"13\" data-col=\"1\">0.408</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n## 5. Re-checking Linearity\n\n::: columns\n::: {.column width=\"50%\"}\nBefore:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](mk68-07-slides_files/figure-revealjs/unnamed-chunk-19-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n::: fragment\nAfter the log transformation:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](mk68-07-slides_files/figure-revealjs/unnamed-chunk-20-1.png){width=100%}\n:::\n:::\n\n:::\n:::\n:::\n\n## 6.1 Results interpretation {.smaller}\n\n::: columns\n::: {.column width=\"55%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_4y674ozt45z93auui4vi(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_4y674ozt45z93auui4vi\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_4y674ozt45z93auui4vi(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_4y674ozt45z93auui4vi\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '13', j: 1 },  ], css_id: 'tinytable_css_3fch0l7b1c9vel7oh09k',}, \n          { positions: [ { i: '10', j: 1 },  ], css_id: 'tinytable_css_p702wzza6x0sj3r9645i',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 },  ], css_id: 'tinytable_css_aec9j4a0k21jp99yfzg8',}, \n          { positions: [ { i: '0', j: 1 },  ], css_id: 'tinytable_css_pyew92jqwqydzco8s84y',}, \n          { positions: [ { i: '13', j: 0 },  ], css_id: 'tinytable_css_8d5a8n3ynxqqrtw2y8gl',}, \n          { positions: [ { i: '10', j: 0 },  ], css_id: 'tinytable_css_9hho70s5bez1xr2rhm7i',}, \n          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 }, { i: '3', j: 0 }, { i: '4', j: 0 }, { i: '5', j: 0 }, { i: '6', j: 0 }, { i: '7', j: 0 }, { i: '8', j: 0 }, { i: '9', j: 0 }, { i: '11', j: 0 }, { i: '12', j: 0 },  ], css_id: 'tinytable_css_1dw02re5jgvlg5vjfd79',}, \n          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_iwoaadwxywcqyn08e3f2',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_4y674ozt45z93auui4vi(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_3fch0l7b1c9vel7oh09k, .table th.tinytable_css_3fch0l7b1c9vel7oh09k { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_p702wzza6x0sj3r9645i, .table th.tinytable_css_p702wzza6x0sj3r9645i { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_aec9j4a0k21jp99yfzg8, .table th.tinytable_css_aec9j4a0k21jp99yfzg8 { text-align: center; }\n      .table td.tinytable_css_pyew92jqwqydzco8s84y, .table th.tinytable_css_pyew92jqwqydzco8s84y { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_8d5a8n3ynxqqrtw2y8gl, .table th.tinytable_css_8d5a8n3ynxqqrtw2y8gl { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_9hho70s5bez1xr2rhm7i, .table th.tinytable_css_9hho70s5bez1xr2rhm7i { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_1dw02re5jgvlg5vjfd79, .table th.tinytable_css_1dw02re5jgvlg5vjfd79 { text-align: left; }\n      .table td.tinytable_css_iwoaadwxywcqyn08e3f2, .table th.tinytable_css_iwoaadwxywcqyn08e3f2 { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_4y674ozt45z93auui4vi\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">log(acrePrice)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>p-values are: '+' p < 0.1, '\\*' p < 0.05, '\\*\\*' p < 0.01, '\\*\\*\\*' p < 0.001. \n    Standard errors are reported in parentheses</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"1\">6.608 (0.042)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">crpPct</td>\n                  <td data-row=\"2\" data-col=\"1\">-0.003 (0.000)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">log(acres)</td>\n                  <td data-row=\"3\" data-col=\"1\">-0.069 (0.007)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">regionWest Central</td>\n                  <td data-row=\"4\" data-col=\"1\">0.624 (0.018)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"0\">regionCentral</td>\n                  <td data-row=\"5\" data-col=\"1\">0.936 (0.021)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"0\">regionSouth West</td>\n                  <td data-row=\"6\" data-col=\"1\">0.712 (0.019)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"0\">regionSouth Central</td>\n                  <td data-row=\"7\" data-col=\"1\">0.849 (0.020)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"0\">regionSouth East</td>\n                  <td data-row=\"8\" data-col=\"1\">0.939 (0.023)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"0\">tillable</td>\n                  <td data-row=\"9\" data-col=\"1\">0.003 (0.000)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"0\">productivity</td>\n                  <td data-row=\"10\" data-col=\"1\">0.009 (0.000)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"0\">Num.Obs.</td>\n                  <td data-row=\"11\" data-col=\"1\">8787</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"0\">R2</td>\n                  <td data-row=\"12\" data-col=\"1\">0.408</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"0\">R2 Adj.</td>\n                  <td data-row=\"13\" data-col=\"1\">0.408</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n:::\n\n::: {.column width=\"45%\"}\nLog transformation requires adjusting the interpretation:\n\n::: fragment\n$\\log(y) = \\beta \\log (x)$ is a **log-log** transformation\n\n-   1 **% (percent)** change in $x$ causes $\\beta$ **% (percent)** change in $y$ (AKA Elasticity).\n:::\n\n::: fragment\n$\\log(y) = \\beta x$ is a **log-level** transformation\n\n-   1 **unit** change in $x$ causes $100 \\beta$ **% (percent)** change in $y$.\n:::\n\n::: fragment\n$y = \\beta \\log(x)$ is a **level-log** transformation\n\n-   1 **% (percent)** change in $x$ causes $\\beta / 100$ **unit** in $y$.\n:::\n\n::: fragment\nEQ: **Interpret selected coefficients and perform statistical hypothesis testing on them.**\n:::\n:::\n:::\n\n## 8. Comparing two models and concluding {.smaller}\n\n::: columns\n::: {.column width=\"70%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_0se9benu96vqumhe0loj(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_0se9benu96vqumhe0loj\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_0se9benu96vqumhe0loj(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_0se9benu96vqumhe0loj\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '14', j: 1 }, { i: '14', j: 2 },  ], css_id: 'tinytable_css_klincaxk67sc30bcfxdb',}, \n          { positions: [ { i: '11', j: 2 }, { i: '11', j: 1 },  ], css_id: 'tinytable_css_ybkh4zz2h9j7c5p8io0n',}, \n          { positions: [ { i: '1', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '9', j: 2 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '12', j: 2 }, { i: '2', j: 1 }, { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '13', j: 2 }, { i: '10', j: 2 },  ], css_id: 'tinytable_css_9ev2954nyex0qi6st70d',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 },  ], css_id: 'tinytable_css_dh3q77rcsr63tah2abva',}, \n          { positions: [ { i: '14', j: 0 },  ], css_id: 'tinytable_css_47p2ffmqmeo22beplahu',}, \n          { positions: [ { i: '11', j: 0 },  ], css_id: 'tinytable_css_bbaz3m0kqibxty3mm4sj',}, \n          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 }, { i: '3', j: 0 }, { i: '4', j: 0 }, { i: '5', j: 0 }, { i: '6', j: 0 }, { i: '7', j: 0 }, { i: '8', j: 0 }, { i: '9', j: 0 }, { i: '10', j: 0 }, { i: '12', j: 0 }, { i: '13', j: 0 },  ], css_id: 'tinytable_css_csjey420qn03w8dz2ho9',}, \n          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_whcb7a2uwoe3cqyp01dg',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_0se9benu96vqumhe0loj(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_klincaxk67sc30bcfxdb, .table th.tinytable_css_klincaxk67sc30bcfxdb { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_ybkh4zz2h9j7c5p8io0n, .table th.tinytable_css_ybkh4zz2h9j7c5p8io0n { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_9ev2954nyex0qi6st70d, .table th.tinytable_css_9ev2954nyex0qi6st70d { text-align: center; }\n      .table td.tinytable_css_dh3q77rcsr63tah2abva, .table th.tinytable_css_dh3q77rcsr63tah2abva { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_47p2ffmqmeo22beplahu, .table th.tinytable_css_47p2ffmqmeo22beplahu { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_bbaz3m0kqibxty3mm4sj, .table th.tinytable_css_bbaz3m0kqibxty3mm4sj { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_csjey420qn03w8dz2ho9, .table th.tinytable_css_csjey420qn03w8dz2ho9 { text-align: left; }\n      .table td.tinytable_css_whcb7a2uwoe3cqyp01dg, .table th.tinytable_css_whcb7a2uwoe3cqyp01dg { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_0se9benu96vqumhe0loj\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">acrePrice</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">log(acrePrice)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='3'>p-values are: '+' p < 0.1, '\\*' p < 0.05, '\\*\\*' p < 0.01, '\\*\\*\\*' p < 0.001. \n    Standard errors are reported in parentheses</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"1\">80.282 (102.349)</td>\n                  <td data-row=\"1\" data-col=\"2\">6.608 (0.042)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">crpPct</td>\n                  <td data-row=\"2\" data-col=\"1\">-6.943 (1.073)***</td>\n                  <td data-row=\"2\" data-col=\"2\">-0.003 (0.000)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">acres</td>\n                  <td data-row=\"3\" data-col=\"1\">-1.290 (0.165)***</td>\n                  <td data-row=\"3\" data-col=\"2\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">regionWest Central</td>\n                  <td data-row=\"4\" data-col=\"1\">995.292 (58.039)***</td>\n                  <td data-row=\"4\" data-col=\"2\">0.624 (0.018)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"0\">regionCentral</td>\n                  <td data-row=\"5\" data-col=\"1\">1950.211 (64.543)***</td>\n                  <td data-row=\"5\" data-col=\"2\">0.936 (0.021)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"0\">regionSouth West</td>\n                  <td data-row=\"6\" data-col=\"1\">1291.828 (58.343)***</td>\n                  <td data-row=\"6\" data-col=\"2\">0.712 (0.019)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"0\">regionSouth Central</td>\n                  <td data-row=\"7\" data-col=\"1\">1747.551 (62.560)***</td>\n                  <td data-row=\"7\" data-col=\"2\">0.849 (0.020)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"0\">regionSouth East</td>\n                  <td data-row=\"8\" data-col=\"1\">2040.677 (72.492)***</td>\n                  <td data-row=\"8\" data-col=\"2\">0.939 (0.023)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"0\">tillable</td>\n                  <td data-row=\"9\" data-col=\"1\">2.112 (0.969)*</td>\n                  <td data-row=\"9\" data-col=\"2\">0.003 (0.000)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"0\">productivity</td>\n                  <td data-row=\"10\" data-col=\"1\">23.690 (1.330)***</td>\n                  <td data-row=\"10\" data-col=\"2\">0.009 (0.000)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"0\">log(acres)</td>\n                  <td data-row=\"11\" data-col=\"1\"></td>\n                  <td data-row=\"11\" data-col=\"2\">-0.069 (0.007)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"0\">Num.Obs.</td>\n                  <td data-row=\"12\" data-col=\"1\">8787</td>\n                  <td data-row=\"12\" data-col=\"2\">8787</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"0\">R2</td>\n                  <td data-row=\"13\" data-col=\"1\">0.265</td>\n                  <td data-row=\"13\" data-col=\"2\">0.408</td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"0\">R2 Adj.</td>\n                  <td data-row=\"14\" data-col=\"1\">0.265</td>\n                  <td data-row=\"14\" data-col=\"2\">0.408</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\nConclude:\n\n::: fragment\nEQ: **Which model would you choose to explain the effect of `crpPct` on the price of land?**\n:::\n\n::: fragment\nEQ: **Which model best explains the relationship between X and Y?**\n:::\n\n::: fragment\n**What is the effect of `crpPct` on land price?**\n:::\n\n::: fragment\n**Which estimated effects are different from your ex-ante hypothesis? Provide a plausible explanation of why are they different?**\n:::\n:::\n:::\n\n\n# Example 2. Production function\n\n---\neditor: source\nformat: \n  revealjs:\n    preview-links: true\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n## 1. Problem setting {.smaller}\n\nWe would like to evaluate the causal effect of the BIMAS production intensification program on the rice output among rice-producing farmers in India.\n\n-   The outcome variable is:\n\n    -   `goutput` - gross output of rice in kg per year produced on the farm.\n    \n-   Key variable of interest is:\n    \n    -   `bimas` **variable of interest** is an intensification program. Each farmer either participates in it (yes), partially participate (mixed), or does not participate (no).\n\n-   Other control variables are:\n\n    -   `size` the total area cultivated with rice, measured in hectares;\n    -   `urea` urea application in kilogram\n    -   `phosphate` phosphate application in kilogram\n    -   `hiredlabor` hired labor in hours\n    -   `famlabor` family labor in hours\n\n\n::: {.cell}\n\n:::\n\n\n## 2. Regression model {.smaller}\n\nThe production function is used to estimate the relationship. We consider two main production functions [see @feng2012alternative]:\n\n::: fragment\n1.  Linear [production function](https://en.wikipedia.org/wiki/Production_function), when output is a linear combination of all inputs. (**Write it down**)\n:::\n\n::: fragment\n$$\n\\begin{aligned}\n\\operatorname{goutput} &= \\alpha + \\beta_{1}(\\operatorname{size}) + \\beta_{2}(\\operatorname{bimas}_{\\operatorname{yes}})\\ + \\\\\n&\\quad \\beta_{3}(\\operatorname{bimas}_{\\operatorname{mixed}}) + \\beta_{4}(\\operatorname{famlabor}) + \\beta_{5}(\\operatorname{hiredlabor})\\ + \\\\\n&\\quad \\beta_{6}(\\operatorname{urea}) + \\beta_{7}(\\operatorname{phosphate}) + \\epsilon\n\\end{aligned}\n$$\n:::\n\n::: fragment\n2.  [Cobb-Douglas](https://en.wikipedia.org/wiki/Cobb%E2%80%93Douglas_production_function) production function, when the log of output is a linear combination of logged inputs. (**Write it down**)\n:::\n\n::: fragment\n$$\n\\begin{aligned}\n\\operatorname{log(goutput)} &= \\alpha + \\beta_{1}(\\operatorname{\\log(size)}) + \\beta_{2}(\\operatorname{bimas}_{\\operatorname{yes}})\\ + \\\\\n&\\quad \\beta_{3}(\\operatorname{bimas}_{\\operatorname{mixed}}) + \\beta_{4}(\\operatorname{\\log(famlabor)}) + \\beta_{5}(\\operatorname{\\log(hiredlabor)})\\ + \\\\\n&\\quad \\beta_{6}(\\operatorname{\\log(urea)}) + \\beta_{7}(\\operatorname{\\log(phosphate)}) + \\epsilon\n\\end{aligned}\n$$\n:::\n\n## 2.1 Ex-ante hypotheses about the coefficients\n\n$$\n\\begin{aligned}\n\\operatorname{goutput} &= \\alpha + \\beta_{1}(\\operatorname{size}) + \\beta_{2}(\\operatorname{bimas}_{\\operatorname{yes}})\\ + \\\\\n&\\quad \\beta_{3}(\\operatorname{bimas}_{\\operatorname{mixed}}) + \\beta_{4}(\\operatorname{famlabor}) + \\beta_{5}(\\operatorname{hiredlabor})\\ + \\\\\n&\\quad \\beta_{6}(\\operatorname{urea}) + \\beta_{7}(\\operatorname{phosphate}) + \\epsilon\n\\end{aligned}\n$$\n\nEQ: **Formulate the ex-ante hypotheses about coefficients?**\n\n## 3 Exploratory data analysis {.smaller}\n\n### 3.1 The data\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| goutput|  size|bimas | famlabor| hiredlabor| urea| phosphate|\n|-------:|-----:|:-----|--------:|----------:|----:|---------:|\n|      71| 0.020|no    |       25|          1|    5|         2|\n|     886| 0.282|no    |       66|        365|   30|        10|\n|    6010| 2.898|mixed |      134|       1878|  300|        50|\n|     952| 0.215|no    |      233|         60|   50|        20|\n|     640| 0.143|no    |       68|         56|   51|        25|\n|     280| 0.143|no    |       76|         42|   32|        10|\n|     960| 0.357|no    |       75|        305|   50|        10|\n|     240| 0.184|no    |       71|         40|   40|        10|\n|    1830| 0.575|yes   |      148|        395|  165|        60|\n|    1106| 0.192|no    |      141|         39|   28|        57|\n|    4400| 0.857|mixed |      130|       1015|  200|        50|\n|     436| 0.143|mixed |       33|         98|   50|        50|\n|     450| 0.140|mixed |       89|         39|   25|        50|\n|    2700| 0.400|mixed |      284|        220|  150|        75|\n|    1041| 0.351|no    |       48|        160|   85|        15|\n\n\n:::\n:::\n\n\n## 3.2 Summary statistics {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_wkqqnluti52ck53133ca(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_wkqqnluti52ck53133ca\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_wkqqnluti52ck53133ca(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_wkqqnluti52ck53133ca\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '6', j: 6 }, { i: '6', j: 2 }, { i: '6', j: 4 }, { i: '6', j: 1 }, { i: '6', j: 3 }, { i: '6', j: 5 }, { i: '6', j: 7 },  ], css_id: 'tinytable_css_r5j6hackilsvj2ilvgco',}, \n          { positions: [ { i: '5', j: 3 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '5', j: 4 }, { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '4', j: 5 }, { i: '5', j: 5 }, { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '4', j: 4 }, { i: '4', j: 6 }, { i: '5', j: 6 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '2', j: 5 }, { i: '3', j: 5 }, { i: '3', j: 7 }, { i: '4', j: 7 }, { i: '5', j: 7 }, { i: '1', j: 4 }, { i: '1', j: 6 }, { i: '2', j: 6 }, { i: '3', j: 6 }, { i: '1', j: 7 }, { i: '2', j: 7 }, { i: '1', j: 5 },  ], css_id: 'tinytable_css_0w1xna0fubvfp36vm1xp',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 3 }, { i: '0', j: 5 }, { i: '0', j: 7 }, { i: '0', j: 4 }, { i: '0', j: 6 }, { i: '0', j: 2 },  ], css_id: 'tinytable_css_67wzio67l0dc4n0r33ks',}, \n          { positions: [ { i: '6', j: 0 },  ], css_id: 'tinytable_css_3rlpzblnnrbgfrp6z73f',}, \n          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 }, { i: '3', j: 0 }, { i: '4', j: 0 }, { i: '5', j: 0 },  ], css_id: 'tinytable_css_i96rnwyfnlg56rt3l55p',}, \n          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_n0bnnenrjk959g2hq9vt',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_wkqqnluti52ck53133ca(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_r5j6hackilsvj2ilvgco, .table th.tinytable_css_r5j6hackilsvj2ilvgco { text-align: right; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_0w1xna0fubvfp36vm1xp, .table th.tinytable_css_0w1xna0fubvfp36vm1xp { text-align: right; }\n      .table td.tinytable_css_67wzio67l0dc4n0r33ks, .table th.tinytable_css_67wzio67l0dc4n0r33ks { text-align: right; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_3rlpzblnnrbgfrp6z73f, .table th.tinytable_css_3rlpzblnnrbgfrp6z73f { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_i96rnwyfnlg56rt3l55p, .table th.tinytable_css_i96rnwyfnlg56rt3l55p { text-align: left; }\n      .table td.tinytable_css_n0bnnenrjk959g2hq9vt, .table th.tinytable_css_n0bnnenrjk959g2hq9vt { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_wkqqnluti52ck53133ca\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">N</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Mean</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">SD</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Min</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">Median</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">Max</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"7\">Histogram</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">goutput</td>\n                  <td data-row=\"1\" data-col=\"1\">883</td>\n                  <td data-row=\"1\" data-col=\"2\">1449.76</td>\n                  <td data-row=\"1\" data-col=\"3\">1956.91</td>\n                  <td data-row=\"1\" data-col=\"4\">42.00</td>\n                  <td data-row=\"1\" data-col=\"5\">952.00</td>\n                  <td data-row=\"1\" data-col=\"6\">20960.00</td>\n                  <td data-row=\"1\" data-col=\"7\">▇▁</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">size</td>\n                  <td data-row=\"2\" data-col=\"1\">883</td>\n                  <td data-row=\"2\" data-col=\"2\">0.43</td>\n                  <td data-row=\"2\" data-col=\"3\">0.52</td>\n                  <td data-row=\"2\" data-col=\"4\">0.01</td>\n                  <td data-row=\"2\" data-col=\"5\">0.29</td>\n                  <td data-row=\"2\" data-col=\"6\">5.32</td>\n                  <td data-row=\"2\" data-col=\"7\">▇▂</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">famlabor</td>\n                  <td data-row=\"3\" data-col=\"1\">883</td>\n                  <td data-row=\"3\" data-col=\"2\">152.76</td>\n                  <td data-row=\"3\" data-col=\"3\">147.63</td>\n                  <td data-row=\"3\" data-col=\"4\">1.00</td>\n                  <td data-row=\"3\" data-col=\"5\">113.00</td>\n                  <td data-row=\"3\" data-col=\"6\">1526.00</td>\n                  <td data-row=\"3\" data-col=\"7\">▇▂▁</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">hiredlabor</td>\n                  <td data-row=\"4\" data-col=\"1\">883</td>\n                  <td data-row=\"4\" data-col=\"2\">243.47</td>\n                  <td data-row=\"4\" data-col=\"3\">422.93</td>\n                  <td data-row=\"4\" data-col=\"4\">1.00</td>\n                  <td data-row=\"4\" data-col=\"5\">121.00</td>\n                  <td data-row=\"4\" data-col=\"6\">4536.00</td>\n                  <td data-row=\"4\" data-col=\"7\">▇▁</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"0\">urea</td>\n                  <td data-row=\"5\" data-col=\"1\">883</td>\n                  <td data-row=\"5\" data-col=\"2\">99.80</td>\n                  <td data-row=\"5\" data-col=\"3\">128.00</td>\n                  <td data-row=\"5\" data-col=\"4\">1.00</td>\n                  <td data-row=\"5\" data-col=\"5\">65.00</td>\n                  <td data-row=\"5\" data-col=\"6\">1250.00</td>\n                  <td data-row=\"5\" data-col=\"7\">▇▁</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"0\">phosphate</td>\n                  <td data-row=\"6\" data-col=\"1\">883</td>\n                  <td data-row=\"6\" data-col=\"2\">39.19</td>\n                  <td data-row=\"6\" data-col=\"3\">49.17</td>\n                  <td data-row=\"6\" data-col=\"4\">1.00</td>\n                  <td data-row=\"6\" data-col=\"5\">25.00</td>\n                  <td data-row=\"6\" data-col=\"6\">700.00</td>\n                  <td data-row=\"6\" data-col=\"7\">▇▁</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_c1adh8cc04nfkqhgj1rz(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_c1adh8cc04nfkqhgj1rz\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_c1adh8cc04nfkqhgj1rz(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_c1adh8cc04nfkqhgj1rz\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '3', j: 1 }, { i: '3', j: 2 },  ], css_id: 'tinytable_css_86gbdmmnhgvkjf2lk21m',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '1', j: 2 }, { i: '2', j: 2 },  ], css_id: 'tinytable_css_zu1e0na6rs5a7vilu3df',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 },  ], css_id: 'tinytable_css_g1c7n2rz6whj2oao5hhs',}, \n          { positions: [ { i: '3', j: 0 },  ], css_id: 'tinytable_css_ics81aw6adw7yli3pvus',}, \n          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 },  ], css_id: 'tinytable_css_dw10k78vgauky46gwfeh',}, \n          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_mqg2xx9wsso3jxg6t0rn',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_c1adh8cc04nfkqhgj1rz(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_86gbdmmnhgvkjf2lk21m, .table th.tinytable_css_86gbdmmnhgvkjf2lk21m { text-align: right; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_zu1e0na6rs5a7vilu3df, .table th.tinytable_css_zu1e0na6rs5a7vilu3df { text-align: right; }\n      .table td.tinytable_css_g1c7n2rz6whj2oao5hhs, .table th.tinytable_css_g1c7n2rz6whj2oao5hhs { text-align: right; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_ics81aw6adw7yli3pvus, .table th.tinytable_css_ics81aw6adw7yli3pvus { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_dw10k78vgauky46gwfeh, .table th.tinytable_css_dw10k78vgauky46gwfeh { text-align: left; }\n      .table td.tinytable_css_mqg2xx9wsso3jxg6t0rn, .table th.tinytable_css_mqg2xx9wsso3jxg6t0rn { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_c1adh8cc04nfkqhgj1rz\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\">bimas</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">N</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">%</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">no</td>\n                  <td data-row=\"1\" data-col=\"1\">661</td>\n                  <td data-row=\"1\" data-col=\"2\">74.9</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">yes</td>\n                  <td data-row=\"2\" data-col=\"1\">84</td>\n                  <td data-row=\"2\" data-col=\"2\">9.5</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">mixed</td>\n                  <td data-row=\"3\" data-col=\"1\">138</td>\n                  <td data-row=\"3\" data-col=\"2\">15.6</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n## 3.3 What effect BIMAS program have? {.smaller}\n\n::: columns\n::: {.column width=\"75%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](mk68-07-slides_files/figure-revealjs/unnamed-chunk-30-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"25%\"}\n-  What kind of plot is this?\n-  What can we conclude about the differences in rice output by program participation?\n-  EQ: **Does the program participation cause rice output to be different?**\n:::\n:::\n\n## 3.4 Distributions\n\n::: columns\n::: {.column width=\"75%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](mk68-07-slides_files/figure-revealjs/unnamed-chunk-31-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"25%\"}\n-   What kind of plot is this?\n-   What does it show?\n-   What differences and similarities does it manifest?\n:::\n:::\n\n## 3.5 Scatter plots\n\n::: r-stack\n\n::: {.cell}\n::: {.cell-output-display}\n![](mk68-07-slides_files/figure-revealjs/unnamed-chunk-32-1.png){width=100%}\n:::\n:::\n\n\n::: fragment\n\n::: {.cell}\n::: {.cell-output-display}\n![](mk68-07-slides_files/figure-revealjs/unnamed-chunk-33-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: fragment\n\n::: {.cell}\n::: {.cell-output-display}\n![](mk68-07-slides_files/figure-revealjs/unnamed-chunk-34-1.png){width=100%}\n:::\n:::\n\n:::\n:::\n\n## 4. Estimating a regression\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"1-3,7-14,16-18\"}\nfit_rice_0 <- lm(\n  goutput ~ size + bimas + famlabor + hiredlabor + urea + phosphate, \n  rice_dta_0)\nsummary(fit_rice_0)\n# Coefficients:\n#               Estimate Std. Error t value Pr(>|t|)    \n# (Intercept) -107.91531   38.36178  -2.813 0.005017 ** \n# size        1824.02155  138.40695  13.179  < 2e-16 ***\n# bimasyes     157.87341   83.12605   1.899 0.057866 .  \n# bimasmixed  -262.07581   68.13525  -3.846 0.000129 ***\n# famlabor       0.78902    0.18633   4.234 2.53e-05 ***\n# hiredlabor     1.03722    0.13132   7.898 8.47e-15 ***\n# urea          -0.03429    0.39242  -0.087 0.930381    \n# phosphate     11.08610    0.74446  14.891  < 2e-16 ***\n# \n# Residual standard error: 706.6 on 875 degrees of freedom\n# Multiple R-squared:  0.8707,\tAdjusted R-squared:  0.8696 \n# F-statistic: 841.5 on 7 and 875 DF,  p-value: < 2.2e-16\n```\n:::\n\n\n## 6. Interpretation (0) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n$$\n\\begin{aligned}\n\\operatorname{\\widehat{goutput}} &= -107.92 + 1824.02(\\operatorname{size})\\ + \\\\\n&\\quad 157.87(\\operatorname{bimas}_{\\operatorname{yes}}) - 262.08(\\operatorname{bimas}_{\\operatorname{mixed}})\\ + \\\\\n&\\quad 0.79(\\operatorname{famlabor}) + 1.04(\\operatorname{hiredlabor})\\ - \\\\\n&\\quad 0.03(\\operatorname{urea}) + 11.09(\\operatorname{phosphate})\n\\end{aligned}\n$$\n\n::: fragment\nThis first regression is in `level-level` form (without any linear transformation). Thus, interpretations are straightforward:\n\n-  1 unit change in $x$ causes $\\hat \\beta$ unit change in $y$.\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_8ybkbq0g8juxqdhz93hq(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_8ybkbq0g8juxqdhz93hq\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_8ybkbq0g8juxqdhz93hq(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_8ybkbq0g8juxqdhz93hq\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '12', j: 1 },  ], css_id: 'tinytable_css_cnrhskbrmzwmuymesxo3',}, \n          { positions: [ { i: '10', j: 1 },  ], css_id: 'tinytable_css_n5cli8vaac9qrac11vvs',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 },  ], css_id: 'tinytable_css_natgbhwdxsdp81m75kga',}, \n          { positions: [ { i: '0', j: 1 },  ], css_id: 'tinytable_css_asalm9coxrl7tr8w6hgf',}, \n          { positions: [ { i: '12', j: 0 },  ], css_id: 'tinytable_css_rnmte23vg8l4dpykrcov',}, \n          { positions: [ { i: '10', j: 0 },  ], css_id: 'tinytable_css_rb8evwz8fxqeu87evz2g',}, \n          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 }, { i: '3', j: 0 }, { i: '4', j: 0 }, { i: '5', j: 0 }, { i: '6', j: 0 }, { i: '7', j: 0 }, { i: '8', j: 0 }, { i: '9', j: 0 }, { i: '11', j: 0 },  ], css_id: 'tinytable_css_uysdunbd7eozf5le9vsj',}, \n          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_4e0za94aexo1g4ilku73',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_8ybkbq0g8juxqdhz93hq(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_cnrhskbrmzwmuymesxo3, .table th.tinytable_css_cnrhskbrmzwmuymesxo3 { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_n5cli8vaac9qrac11vvs, .table th.tinytable_css_n5cli8vaac9qrac11vvs { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_natgbhwdxsdp81m75kga, .table th.tinytable_css_natgbhwdxsdp81m75kga { text-align: center; }\n      .table td.tinytable_css_asalm9coxrl7tr8w6hgf, .table th.tinytable_css_asalm9coxrl7tr8w6hgf { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_rnmte23vg8l4dpykrcov, .table th.tinytable_css_rnmte23vg8l4dpykrcov { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_rb8evwz8fxqeu87evz2g, .table th.tinytable_css_rb8evwz8fxqeu87evz2g { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_uysdunbd7eozf5le9vsj, .table th.tinytable_css_uysdunbd7eozf5le9vsj { text-align: left; }\n      .table td.tinytable_css_4e0za94aexo1g4ilku73, .table th.tinytable_css_4e0za94aexo1g4ilku73 { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_8ybkbq0g8juxqdhz93hq\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Linear prod. fun (level-level)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>p-values are '+' p < 0.1, '\\*' p < 0.05, '\\*\\*' p < 0.01, '\\*\\*\\*' p < 0.001. Standard errors are reported in parentheses</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">Dep. var.</td>\n                  <td data-row=\"1\" data-col=\"1\">Rice output, kg</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">(Intercept)</td>\n                  <td data-row=\"2\" data-col=\"1\">-107.915 (38.362)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">Size, HA</td>\n                  <td data-row=\"3\" data-col=\"1\">1824.022 (138.407)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">BIMAS [YES]</td>\n                  <td data-row=\"4\" data-col=\"1\">157.873 (83.126)+</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"0\">BIMAS [MIXED]</td>\n                  <td data-row=\"5\" data-col=\"1\">-262.076 (68.135)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"0\">Family labor, h</td>\n                  <td data-row=\"6\" data-col=\"1\">0.789 (0.186)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"0\">Hired labor, h</td>\n                  <td data-row=\"7\" data-col=\"1\">1.037 (0.131)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"0\">Urea, kg</td>\n                  <td data-row=\"8\" data-col=\"1\">-0.034 (0.392)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"0\">Phosphate, kg</td>\n                  <td data-row=\"9\" data-col=\"1\">11.086 (0.744)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"0\">Num.Obs.</td>\n                  <td data-row=\"10\" data-col=\"1\">883</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"0\">R2</td>\n                  <td data-row=\"11\" data-col=\"1\">0.871</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"0\">R2 Adj.</td>\n                  <td data-row=\"12\" data-col=\"1\">0.870</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n:::\n:::\n\n## 6. Interpretation (1) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n`size` is the total area cultivated with rice, measured in hectares.\n\n-   An increase in the farm size by 1 hectare, causes on average the gross output of rice to increase by 1824 kg, holding all other factors constant.\n\n-   The effect of farm size is significant at the 0.1% level of significance ($H_0$ is rejected based on the p-value, which is p \\< 0.001 given \"\\*\\*\\*\") suggesting that a positive relationship between the farm size and output is likely to be present in the population.\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_giu0rc53q8wgi5xx7xvm(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_giu0rc53q8wgi5xx7xvm\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_giu0rc53q8wgi5xx7xvm(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_giu0rc53q8wgi5xx7xvm\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '12', j: 1 },  ], css_id: 'tinytable_css_g8p702wzza6x0sj3r964',}, \n          { positions: [ { i: '10', j: 1 },  ], css_id: 'tinytable_css_4yaec9j4a0k21jp99yfz',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 },  ], css_id: 'tinytable_css_glpyew92jqwqydzco8s8',}, \n          { positions: [ { i: '0', j: 1 },  ], css_id: 'tinytable_css_7i8d5a8n3ynxqqrtw2y8',}, \n          { positions: [ { i: '12', j: 0 },  ], css_id: 'tinytable_css_799hho70s5bez1xr2rhm',}, \n          { positions: [ { i: '10', j: 0 },  ], css_id: 'tinytable_css_f21dw02re5jgvlg5vjfd',}, \n          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 }, { i: '3', j: 0 }, { i: '4', j: 0 }, { i: '5', j: 0 }, { i: '6', j: 0 }, { i: '7', j: 0 }, { i: '8', j: 0 }, { i: '9', j: 0 }, { i: '11', j: 0 },  ], css_id: 'tinytable_css_viiwoaadwxywcqyn08e3',}, \n          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_3y4y674ozt45z93auui4',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_giu0rc53q8wgi5xx7xvm(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_g8p702wzza6x0sj3r964, .table th.tinytable_css_g8p702wzza6x0sj3r964 { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_4yaec9j4a0k21jp99yfz, .table th.tinytable_css_4yaec9j4a0k21jp99yfz { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_glpyew92jqwqydzco8s8, .table th.tinytable_css_glpyew92jqwqydzco8s8 { text-align: center; }\n      .table td.tinytable_css_7i8d5a8n3ynxqqrtw2y8, .table th.tinytable_css_7i8d5a8n3ynxqqrtw2y8 { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_799hho70s5bez1xr2rhm, .table th.tinytable_css_799hho70s5bez1xr2rhm { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_f21dw02re5jgvlg5vjfd, .table th.tinytable_css_f21dw02re5jgvlg5vjfd { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_viiwoaadwxywcqyn08e3, .table th.tinytable_css_viiwoaadwxywcqyn08e3 { text-align: left; }\n      .table td.tinytable_css_3y4y674ozt45z93auui4, .table th.tinytable_css_3y4y674ozt45z93auui4 { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_giu0rc53q8wgi5xx7xvm\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Linear prod. fun (level-level)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>p-values are '+' p < 0.1, '\\*' p < 0.05, '\\*\\*' p < 0.01, '\\*\\*\\*' p < 0.001. Standard errors are reported in parentheses</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">Dep. var.</td>\n                  <td data-row=\"1\" data-col=\"1\">Rice output, kg</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">(Intercept)</td>\n                  <td data-row=\"2\" data-col=\"1\">-107.915 (38.362)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">Size, HA</td>\n                  <td data-row=\"3\" data-col=\"1\">1824.022 (138.407)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">BIMAS [YES]</td>\n                  <td data-row=\"4\" data-col=\"1\">157.873 (83.126)+</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"0\">BIMAS [MIXED]</td>\n                  <td data-row=\"5\" data-col=\"1\">-262.076 (68.135)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"0\">Family labor, h</td>\n                  <td data-row=\"6\" data-col=\"1\">0.789 (0.186)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"0\">Hired labor, h</td>\n                  <td data-row=\"7\" data-col=\"1\">1.037 (0.131)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"0\">Urea, kg</td>\n                  <td data-row=\"8\" data-col=\"1\">-0.034 (0.392)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"0\">Phosphate, kg</td>\n                  <td data-row=\"9\" data-col=\"1\">11.086 (0.744)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"0\">Num.Obs.</td>\n                  <td data-row=\"10\" data-col=\"1\">883</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"0\">R2</td>\n                  <td data-row=\"11\" data-col=\"1\">0.871</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"0\">R2 Adj.</td>\n                  <td data-row=\"12\" data-col=\"1\">0.870</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n:::\n:::\n\n## 6. Interpretation (2) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n::: {.callout-note appearance=\"simple\"}\n`bimas` is an intensification program. Each farmer either:\n\n-   participate in it \\[YES\\], or partially participate \\[MIXED\\] or do not participate \\[NO\\].\n\n-   Because the dummy variable for \\[NO\\] is omitted, it is implied in the intercept.\n\n-   Variables \\[YES\\] and \\[MIXED\\] show the effect of different levels of participation **compared to NO (non-participation in BIMAS)**.\n:::\n\n-   Participating in the BIMAS on a MIXED basis reduces the gross output of rice by 262 kg compared to non-participation given that all other factors remain fixed. The effect is significant at the 5% level of significance.\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_9kyzji0sg3wwimmuy76m(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_9kyzji0sg3wwimmuy76m\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_9kyzji0sg3wwimmuy76m(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_9kyzji0sg3wwimmuy76m\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '12', j: 1 },  ], css_id: 'tinytable_css_va9ev2954nyex0qi6st7',}, \n          { positions: [ { i: '10', j: 1 },  ], css_id: 'tinytable_css_hudh3q77rcsr63tah2ab',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 },  ], css_id: 'tinytable_css_sj47p2ffmqmeo22bepla',}, \n          { positions: [ { i: '0', j: 1 },  ], css_id: 'tinytable_css_o9bbaz3m0kqibxty3mm4',}, \n          { positions: [ { i: '12', j: 0 },  ], css_id: 'tinytable_css_dgcsjey420qn03w8dz2h',}, \n          { positions: [ { i: '10', j: 0 },  ], css_id: 'tinytable_css_ojwhcb7a2uwoe3cqyp01',}, \n          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 }, { i: '3', j: 0 }, { i: '4', j: 0 }, { i: '5', j: 0 }, { i: '6', j: 0 }, { i: '7', j: 0 }, { i: '8', j: 0 }, { i: '9', j: 0 }, { i: '11', j: 0 },  ], css_id: 'tinytable_css_6k0se9benu96vqumhe0l',}, \n          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_xcvs9our7r7f2nldrhz4',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_9kyzji0sg3wwimmuy76m(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_va9ev2954nyex0qi6st7, .table th.tinytable_css_va9ev2954nyex0qi6st7 { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_hudh3q77rcsr63tah2ab, .table th.tinytable_css_hudh3q77rcsr63tah2ab { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_sj47p2ffmqmeo22bepla, .table th.tinytable_css_sj47p2ffmqmeo22bepla { text-align: center; }\n      .table td.tinytable_css_o9bbaz3m0kqibxty3mm4, .table th.tinytable_css_o9bbaz3m0kqibxty3mm4 { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_dgcsjey420qn03w8dz2h, .table th.tinytable_css_dgcsjey420qn03w8dz2h { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_ojwhcb7a2uwoe3cqyp01, .table th.tinytable_css_ojwhcb7a2uwoe3cqyp01 { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_6k0se9benu96vqumhe0l, .table th.tinytable_css_6k0se9benu96vqumhe0l { text-align: left; }\n      .table td.tinytable_css_xcvs9our7r7f2nldrhz4, .table th.tinytable_css_xcvs9our7r7f2nldrhz4 { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_9kyzji0sg3wwimmuy76m\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Linear prod. fun (level-level)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>p-values are '+' p < 0.1, '\\*' p < 0.05, '\\*\\*' p < 0.01, '\\*\\*\\*' p < 0.001. Standard errors are reported in parentheses</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">Dep. var.</td>\n                  <td data-row=\"1\" data-col=\"1\">Rice output, kg</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">(Intercept)</td>\n                  <td data-row=\"2\" data-col=\"1\">-107.915 (38.362)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">Size, HA</td>\n                  <td data-row=\"3\" data-col=\"1\">1824.022 (138.407)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">BIMAS [YES]</td>\n                  <td data-row=\"4\" data-col=\"1\">157.873 (83.126)+</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"0\">BIMAS [MIXED]</td>\n                  <td data-row=\"5\" data-col=\"1\">-262.076 (68.135)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"0\">Family labor, h</td>\n                  <td data-row=\"6\" data-col=\"1\">0.789 (0.186)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"0\">Hired labor, h</td>\n                  <td data-row=\"7\" data-col=\"1\">1.037 (0.131)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"0\">Urea, kg</td>\n                  <td data-row=\"8\" data-col=\"1\">-0.034 (0.392)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"0\">Phosphate, kg</td>\n                  <td data-row=\"9\" data-col=\"1\">11.086 (0.744)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"0\">Num.Obs.</td>\n                  <td data-row=\"10\" data-col=\"1\">883</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"0\">R2</td>\n                  <td data-row=\"11\" data-col=\"1\">0.871</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"0\">R2 Adj.</td>\n                  <td data-row=\"12\" data-col=\"1\">0.870</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n:::\n:::\n\n## 6. Interpretation (3) {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n::: {.callout-note appearance=\"simple\"}\n-   Fully participating in the BIMAS program \\[YES\\] yields an estimate of the coefficient of 157.8 implying on average a 158 kg increase in rice production; however, this result is insignificant at the 5% level.\n\n-   The present functional form fails to reject $H_0$ about the significant difference of this estimate from zero concluding that such an effect may result from the random variation in the sample, rather than exist in the population.\n\n-   To further investigate this effect, we might consider modifying the functional form or collecting more data.\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_0nklincaxk67sc30bcfx(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_0nklincaxk67sc30bcfx\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_0nklincaxk67sc30bcfx(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_0nklincaxk67sc30bcfx\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '12', j: 1 },  ], css_id: 'tinytable_css_3tfyxar6o2o5260oh6dv',}, \n          { positions: [ { i: '10', j: 1 },  ], css_id: 'tinytable_css_hccw7sgem5za67dg2lyk',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 },  ], css_id: 'tinytable_css_0g3cw0c6djqnaxqkf7g2',}, \n          { positions: [ { i: '0', j: 1 },  ], css_id: 'tinytable_css_ybzriu642bj4a59ggaj0',}, \n          { positions: [ { i: '12', j: 0 },  ], css_id: 'tinytable_css_4inmh5855c8kbk950gbo',}, \n          { positions: [ { i: '10', j: 0 },  ], css_id: 'tinytable_css_4x0xoft2eadh4rt97w0o',}, \n          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 }, { i: '3', j: 0 }, { i: '4', j: 0 }, { i: '5', j: 0 }, { i: '6', j: 0 }, { i: '7', j: 0 }, { i: '8', j: 0 }, { i: '9', j: 0 }, { i: '11', j: 0 },  ], css_id: 'tinytable_css_1kdkhnlzu5q2h5o90j7w',}, \n          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_dbwtr2mc2f4te1p9vvje',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_0nklincaxk67sc30bcfx(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_3tfyxar6o2o5260oh6dv, .table th.tinytable_css_3tfyxar6o2o5260oh6dv { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_hccw7sgem5za67dg2lyk, .table th.tinytable_css_hccw7sgem5za67dg2lyk { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_0g3cw0c6djqnaxqkf7g2, .table th.tinytable_css_0g3cw0c6djqnaxqkf7g2 { text-align: center; }\n      .table td.tinytable_css_ybzriu642bj4a59ggaj0, .table th.tinytable_css_ybzriu642bj4a59ggaj0 { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_4inmh5855c8kbk950gbo, .table th.tinytable_css_4inmh5855c8kbk950gbo { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_4x0xoft2eadh4rt97w0o, .table th.tinytable_css_4x0xoft2eadh4rt97w0o { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_1kdkhnlzu5q2h5o90j7w, .table th.tinytable_css_1kdkhnlzu5q2h5o90j7w { text-align: left; }\n      .table td.tinytable_css_dbwtr2mc2f4te1p9vvje, .table th.tinytable_css_dbwtr2mc2f4te1p9vvje { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_0nklincaxk67sc30bcfx\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Linear prod. fun (level-level)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>p-values are '+' p < 0.1, '\\*' p < 0.05, '\\*\\*' p < 0.01, '\\*\\*\\*' p < 0.001. Standard errors are reported in parentheses</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">Dep. var.</td>\n                  <td data-row=\"1\" data-col=\"1\">Rice output, kg</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">(Intercept)</td>\n                  <td data-row=\"2\" data-col=\"1\">-107.915 (38.362)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">Size, HA</td>\n                  <td data-row=\"3\" data-col=\"1\">1824.022 (138.407)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">BIMAS [YES]</td>\n                  <td data-row=\"4\" data-col=\"1\">157.873 (83.126)+</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"0\">BIMAS [MIXED]</td>\n                  <td data-row=\"5\" data-col=\"1\">-262.076 (68.135)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"0\">Family labor, h</td>\n                  <td data-row=\"6\" data-col=\"1\">0.789 (0.186)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"0\">Hired labor, h</td>\n                  <td data-row=\"7\" data-col=\"1\">1.037 (0.131)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"0\">Urea, kg</td>\n                  <td data-row=\"8\" data-col=\"1\">-0.034 (0.392)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"0\">Phosphate, kg</td>\n                  <td data-row=\"9\" data-col=\"1\">11.086 (0.744)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"0\">Num.Obs.</td>\n                  <td data-row=\"10\" data-col=\"1\">883</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"0\">R2</td>\n                  <td data-row=\"11\" data-col=\"1\">0.871</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"0\">R2 Adj.</td>\n                  <td data-row=\"12\" data-col=\"1\">0.870</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n:::\n:::\n\n## 6. Interpretation (4) DIY {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n::: {.callout-note appearance=\"simple\"}\n-   `urea` or `phosphate` application in kilogram;\n-   `hiredlabor` or `famlabor` in hours;\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_bmxcwhszrgvx5u8xz94n(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_bmxcwhszrgvx5u8xz94n\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_bmxcwhszrgvx5u8xz94n(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_bmxcwhszrgvx5u8xz94n\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '12', j: 1 },  ], css_id: 'tinytable_css_033eza8kc6tje7g9ll9o',}, \n          { positions: [ { i: '10', j: 1 },  ], css_id: 'tinytable_css_35oyluav77h6t8p8jzuh',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 },  ], css_id: 'tinytable_css_ikf4epd1etw3595mz3gs',}, \n          { positions: [ { i: '0', j: 1 },  ], css_id: 'tinytable_css_4rhm7836fc83n20ywhlc',}, \n          { positions: [ { i: '12', j: 0 },  ], css_id: 'tinytable_css_c0ec77yoxmemuifdfcht',}, \n          { positions: [ { i: '10', j: 0 },  ], css_id: 'tinytable_css_8jmq5vlhf6uudtzrbr1y',}, \n          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 }, { i: '3', j: 0 }, { i: '4', j: 0 }, { i: '5', j: 0 }, { i: '6', j: 0 }, { i: '7', j: 0 }, { i: '8', j: 0 }, { i: '9', j: 0 }, { i: '11', j: 0 },  ], css_id: 'tinytable_css_taar7cue92ccp5isgnna',}, \n          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_r4vuxwnwp8kiz8sx98h5',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_bmxcwhszrgvx5u8xz94n(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_033eza8kc6tje7g9ll9o, .table th.tinytable_css_033eza8kc6tje7g9ll9o { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_35oyluav77h6t8p8jzuh, .table th.tinytable_css_35oyluav77h6t8p8jzuh { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_ikf4epd1etw3595mz3gs, .table th.tinytable_css_ikf4epd1etw3595mz3gs { text-align: center; }\n      .table td.tinytable_css_4rhm7836fc83n20ywhlc, .table th.tinytable_css_4rhm7836fc83n20ywhlc { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_c0ec77yoxmemuifdfcht, .table th.tinytable_css_c0ec77yoxmemuifdfcht { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_8jmq5vlhf6uudtzrbr1y, .table th.tinytable_css_8jmq5vlhf6uudtzrbr1y { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_taar7cue92ccp5isgnna, .table th.tinytable_css_taar7cue92ccp5isgnna { text-align: left; }\n      .table td.tinytable_css_r4vuxwnwp8kiz8sx98h5, .table th.tinytable_css_r4vuxwnwp8kiz8sx98h5 { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_bmxcwhszrgvx5u8xz94n\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Linear prod. fun (level-level)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>p-values are '+' p < 0.1, '\\*' p < 0.05, '\\*\\*' p < 0.01, '\\*\\*\\*' p < 0.001. Standard errors are reported in parentheses</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">Dep. var.</td>\n                  <td data-row=\"1\" data-col=\"1\">Rice output, kg</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">(Intercept)</td>\n                  <td data-row=\"2\" data-col=\"1\">-107.915 (38.362)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">Size, HA</td>\n                  <td data-row=\"3\" data-col=\"1\">1824.022 (138.407)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">BIMAS [YES]</td>\n                  <td data-row=\"4\" data-col=\"1\">157.873 (83.126)+</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"0\">BIMAS [MIXED]</td>\n                  <td data-row=\"5\" data-col=\"1\">-262.076 (68.135)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"0\">Family labor, h</td>\n                  <td data-row=\"6\" data-col=\"1\">0.789 (0.186)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"0\">Hired labor, h</td>\n                  <td data-row=\"7\" data-col=\"1\">1.037 (0.131)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"0\">Urea, kg</td>\n                  <td data-row=\"8\" data-col=\"1\">-0.034 (0.392)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"0\">Phosphate, kg</td>\n                  <td data-row=\"9\" data-col=\"1\">11.086 (0.744)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"0\">Num.Obs.</td>\n                  <td data-row=\"10\" data-col=\"1\">883</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"0\">R2</td>\n                  <td data-row=\"11\" data-col=\"1\">0.871</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"0\">R2 Adj.</td>\n                  <td data-row=\"12\" data-col=\"1\">0.870</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n:::\n:::\n\n## 5. Checking the linearity assumption (1)\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](mk68-07-slides_files/figure-revealjs/unnamed-chunk-42-1.png){width=100%}\n:::\n:::\n\n\n-   Clear signs of non-linearity.\n\n## 4. Model re-specification {.smaller}\n\nEstimating the Cobb-Douglas production function. Note, that $\\log(\\cdot)$ stands for a natural logarithm.\n\n$$\n\\begin{aligned}\n\\operatorname{\\widehat{log(goutput)}} &= 5.72 + 0.55(\\operatorname{\\log(size)}) + 0.12(\\operatorname{bimas}_{\\operatorname{yes}})\\ - \\\\\n&\\quad 0.14(\\operatorname{bimas}_{\\operatorname{mixed}}) + 0.04(\\operatorname{\\log(famlabor)}) + 0.03(\\operatorname{\\log(hiredlabor)})\\ + \\\\\n&\\quad 0.25(\\operatorname{\\log(urea)}) + 0.13(\\operatorname{\\log(phosphate)})\n\\end{aligned}\n$$\n\n## 4.1 Comparing regressions {.smaller}\n\n::: columns\n::: {.column width=\"80%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_3zrp9j02pl0jwkj48o8f(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_3zrp9j02pl0jwkj48o8f\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_3zrp9j02pl0jwkj48o8f(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_3zrp9j02pl0jwkj48o8f\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '13', j: 1 }, { i: '13', j: 2 },  ], css_id: 'tinytable_css_4fbjf9bhh1tzj6yoo5pn',}, \n          { positions: [ { i: '11', j: 1 }, { i: '11', j: 2 },  ], css_id: 'tinytable_css_ilgaaz6lmy35usmnlb8a',}, \n          { positions: [ { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '10', j: 2 }, { i: '12', j: 1 }, { i: '12', j: 2 }, { i: '1', j: 1 }, { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 },  ], css_id: 'tinytable_css_e36rez5dzqb8i36wes01',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 },  ], css_id: 'tinytable_css_dr8848gwwuecgza19udl',}, \n          { positions: [ { i: '13', j: 0 },  ], css_id: 'tinytable_css_fjz2kwfs0rh1gsmjpl7t',}, \n          { positions: [ { i: '11', j: 0 },  ], css_id: 'tinytable_css_lavly5evw1rsvd10x5p1',}, \n          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 }, { i: '3', j: 0 }, { i: '4', j: 0 }, { i: '5', j: 0 }, { i: '6', j: 0 }, { i: '7', j: 0 }, { i: '8', j: 0 }, { i: '9', j: 0 }, { i: '10', j: 0 }, { i: '12', j: 0 },  ], css_id: 'tinytable_css_gm3kvj2h3vshm4lanrn3',}, \n          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_9eakfdsxspuh10gxxj5v',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_3zrp9j02pl0jwkj48o8f(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_4fbjf9bhh1tzj6yoo5pn, .table th.tinytable_css_4fbjf9bhh1tzj6yoo5pn { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_ilgaaz6lmy35usmnlb8a, .table th.tinytable_css_ilgaaz6lmy35usmnlb8a { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_e36rez5dzqb8i36wes01, .table th.tinytable_css_e36rez5dzqb8i36wes01 { text-align: center; }\n      .table td.tinytable_css_dr8848gwwuecgza19udl, .table th.tinytable_css_dr8848gwwuecgza19udl { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_fjz2kwfs0rh1gsmjpl7t, .table th.tinytable_css_fjz2kwfs0rh1gsmjpl7t { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_lavly5evw1rsvd10x5p1, .table th.tinytable_css_lavly5evw1rsvd10x5p1 { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_gm3kvj2h3vshm4lanrn3, .table th.tinytable_css_gm3kvj2h3vshm4lanrn3 { text-align: left; }\n      .table td.tinytable_css_9eakfdsxspuh10gxxj5v, .table th.tinytable_css_9eakfdsxspuh10gxxj5v { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_3zrp9j02pl0jwkj48o8f\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Linear (level-level)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Cobb-Douglas(log-log)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='3'>p-values are '+' p < 0.1, '\\*' p < 0.05, '\\*\\*' p < 0.01, '\\*\\*\\*' p < 0.001. Standard errors are reported in parentheses</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">Dep. var.</td>\n                  <td data-row=\"1\" data-col=\"1\">Rice output, kg</td>\n                  <td data-row=\"1\" data-col=\"2\">log(Rice output, kg)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">BIMAS [YES]</td>\n                  <td data-row=\"2\" data-col=\"1\">157.873 (83.126)+</td>\n                  <td data-row=\"2\" data-col=\"2\">0.118 (0.041)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">BIMAS [MIXED]</td>\n                  <td data-row=\"3\" data-col=\"1\">-262.076 (68.135)***</td>\n                  <td data-row=\"3\" data-col=\"2\">-0.142 (0.033)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">Size, HA</td>\n                  <td data-row=\"4\" data-col=\"1\">1824.022 (138.407)***</td>\n                  <td data-row=\"4\" data-col=\"2\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"0\">log(Size, HA)</td>\n                  <td data-row=\"5\" data-col=\"1\"></td>\n                  <td data-row=\"5\" data-col=\"2\">0.555 (0.027)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"0\">Family labor, h</td>\n                  <td data-row=\"6\" data-col=\"1\">0.789 (0.186)***</td>\n                  <td data-row=\"6\" data-col=\"2\">0.042 (0.015)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"0\">Hired labor, h</td>\n                  <td data-row=\"7\" data-col=\"1\">1.037 (0.131)***</td>\n                  <td data-row=\"7\" data-col=\"2\">0.035 (0.011)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"0\">Urea, kg</td>\n                  <td data-row=\"8\" data-col=\"1\">-0.034 (0.392)</td>\n                  <td data-row=\"8\" data-col=\"2\">0.247 (0.028)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"0\">Phosphate, kg</td>\n                  <td data-row=\"9\" data-col=\"1\">11.086 (0.744)***</td>\n                  <td data-row=\"9\" data-col=\"2\">0.133 (0.021)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"0\">(Intercept)</td>\n                  <td data-row=\"10\" data-col=\"1\">-107.915 (38.362)**</td>\n                  <td data-row=\"10\" data-col=\"2\">5.721 (0.150)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"0\">Num.Obs.</td>\n                  <td data-row=\"11\" data-col=\"1\">883</td>\n                  <td data-row=\"11\" data-col=\"2\">883</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"0\">R2</td>\n                  <td data-row=\"12\" data-col=\"1\">0.871</td>\n                  <td data-row=\"12\" data-col=\"2\">0.878</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"0\">R2 Adj.</td>\n                  <td data-row=\"13\" data-col=\"1\">0.870</td>\n                  <td data-row=\"13\" data-col=\"2\">0.877</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n:::\n\n::: {.column width=\"20%\"}\n-  What has changed?\n\n-  Has any coefficient changed the sign?\n\n-  Has any coefficient become significant / insignificant?\n\n-  How have the goodness of fit measures (GOF) changed?\n:::\n:::\n\n## 5. (Again) Checking Linearity {.smaller}\n\n::: columns\n::: {.column width=\"50%\"}\n**Linear production function**\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](mk68-07-slides_files/figure-revealjs/unnamed-chunk-45-1.png){width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n**Cobb-Douglas production function** \n\n::: fragment\n\n::: {.cell}\n::: {.cell-output-display}\n![](mk68-07-slides_files/figure-revealjs/unnamed-chunk-46-1.png){width=100%}\n:::\n:::\n\n:::\n\n:::\n:::\n\n\n::: fragment\nSubstantial improvement in linearity.\n:::\n\n## 6. Interpretation with log (0) {.smaller}\n\n::: columns\n::: {.column width=\"45%\"}\nThis regression is in the `log-log` transformation for all variables except for the dummy variables, which are in the `log-level`.\n\n`log-log` interpretation is straightforward:\n\n-   1 % percent increase in $x$ causes $\\hat \\beta$ % (percent) change in $y$.\n:::\n\n::: {.column width=\"55%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_0c30femg8v6d86vn51bm(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_0c30femg8v6d86vn51bm\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_0c30femg8v6d86vn51bm(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_0c30femg8v6d86vn51bm\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '12', j: 1 },  ], css_id: 'tinytable_css_v7opf8wqlsdns70k8xs1',}, \n          { positions: [ { i: '10', j: 1 },  ], css_id: 'tinytable_css_sm5ng1opqnyt4s7olv2u',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 },  ], css_id: 'tinytable_css_06my7xgzhq8n6oio3052',}, \n          { positions: [ { i: '0', j: 1 },  ], css_id: 'tinytable_css_pssnov8ij6yhjbiwyv47',}, \n          { positions: [ { i: '12', j: 0 },  ], css_id: 'tinytable_css_6o6pe568xdeyl1ajtzxa',}, \n          { positions: [ { i: '10', j: 0 },  ], css_id: 'tinytable_css_gx59m226foroc6o5viij',}, \n          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 }, { i: '3', j: 0 }, { i: '4', j: 0 }, { i: '5', j: 0 }, { i: '6', j: 0 }, { i: '7', j: 0 }, { i: '8', j: 0 }, { i: '9', j: 0 }, { i: '11', j: 0 },  ], css_id: 'tinytable_css_aji5y40cxawu1623rc9v',}, \n          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_8wt22fz952jerwxe45lg',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_0c30femg8v6d86vn51bm(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_v7opf8wqlsdns70k8xs1, .table th.tinytable_css_v7opf8wqlsdns70k8xs1 { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_sm5ng1opqnyt4s7olv2u, .table th.tinytable_css_sm5ng1opqnyt4s7olv2u { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_06my7xgzhq8n6oio3052, .table th.tinytable_css_06my7xgzhq8n6oio3052 { text-align: center; }\n      .table td.tinytable_css_pssnov8ij6yhjbiwyv47, .table th.tinytable_css_pssnov8ij6yhjbiwyv47 { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_6o6pe568xdeyl1ajtzxa, .table th.tinytable_css_6o6pe568xdeyl1ajtzxa { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_gx59m226foroc6o5viij, .table th.tinytable_css_gx59m226foroc6o5viij { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_aji5y40cxawu1623rc9v, .table th.tinytable_css_aji5y40cxawu1623rc9v { text-align: left; }\n      .table td.tinytable_css_8wt22fz952jerwxe45lg, .table th.tinytable_css_8wt22fz952jerwxe45lg { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_0c30femg8v6d86vn51bm\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Cobb-Douglas (log-log)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>p-values are '+' p < 0.1, '\\*' p < 0.05, '\\*\\*' p < 0.01, '\\*\\*\\*' p < 0.001. Standard errors are reported in parentheses</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">Dep. var.</td>\n                  <td data-row=\"1\" data-col=\"1\">log(Rice output, kg)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">BIMAS [YES]</td>\n                  <td data-row=\"2\" data-col=\"1\">0.118 (0.041)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">BIMAS [MIXED]</td>\n                  <td data-row=\"3\" data-col=\"1\">-0.142 (0.033)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">log(Size, HA)</td>\n                  <td data-row=\"4\" data-col=\"1\">0.555 (0.027)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"0\">Family labor, h</td>\n                  <td data-row=\"5\" data-col=\"1\">0.042 (0.015)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"0\">Hired labor, h</td>\n                  <td data-row=\"6\" data-col=\"1\">0.035 (0.011)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"0\">Urea, kg</td>\n                  <td data-row=\"7\" data-col=\"1\">0.247 (0.028)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"0\">Phosphate, kg</td>\n                  <td data-row=\"8\" data-col=\"1\">0.133 (0.021)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"0\">(Intercept)</td>\n                  <td data-row=\"9\" data-col=\"1\">5.721 (0.150)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"0\">Num.Obs.</td>\n                  <td data-row=\"10\" data-col=\"1\">883</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"0\">R2</td>\n                  <td data-row=\"11\" data-col=\"1\">0.878</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"0\">R2 Adj.</td>\n                  <td data-row=\"12\" data-col=\"1\">0.877</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n:::\n:::\n\n## 6. Interpretation with log (1) {.smaller}\n\n::: columns\n::: {.column width=\"45%\"}\n`log-level` interpretation of the dummy variables is more complex:\n\n-   For the purpose of the exam, please be able to explain weather the dummy variable has a positive or negative effect on $y$ and if this effect is significant.\n\nFor your information and future, please be informed that:\n\n-   Change (increase) of a dummy variable $x$ from 0 to 1 causes $100 \\cdot (e^{\\hat\\beta} - 1)$ % change in $y$.\n:::\n\n::: {.column width=\"55%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_xdck5ncwmuzg9rgea53b(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_xdck5ncwmuzg9rgea53b\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_xdck5ncwmuzg9rgea53b(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_xdck5ncwmuzg9rgea53b\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '12', j: 1 },  ], css_id: 'tinytable_css_uwofcz6yln4uc4mdr15a',}, \n          { positions: [ { i: '10', j: 1 },  ], css_id: 'tinytable_css_qzihr3n7psm2s6d70z0i',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 },  ], css_id: 'tinytable_css_60k7ozk6uofy7tcrk9gn',}, \n          { positions: [ { i: '0', j: 1 },  ], css_id: 'tinytable_css_1ptdxmwejc6ery1m8v3o',}, \n          { positions: [ { i: '12', j: 0 },  ], css_id: 'tinytable_css_z2esqpsw728nw8e3g9n1',}, \n          { positions: [ { i: '10', j: 0 },  ], css_id: 'tinytable_css_y2qxw7f1of8z6nwtfca0',}, \n          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 }, { i: '3', j: 0 }, { i: '4', j: 0 }, { i: '5', j: 0 }, { i: '6', j: 0 }, { i: '7', j: 0 }, { i: '8', j: 0 }, { i: '9', j: 0 }, { i: '11', j: 0 },  ], css_id: 'tinytable_css_x3moftfndwp8pyleps4o',}, \n          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_ebceetzjboq80uzxvalg',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_xdck5ncwmuzg9rgea53b(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_uwofcz6yln4uc4mdr15a, .table th.tinytable_css_uwofcz6yln4uc4mdr15a { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_qzihr3n7psm2s6d70z0i, .table th.tinytable_css_qzihr3n7psm2s6d70z0i { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_60k7ozk6uofy7tcrk9gn, .table th.tinytable_css_60k7ozk6uofy7tcrk9gn { text-align: center; }\n      .table td.tinytable_css_1ptdxmwejc6ery1m8v3o, .table th.tinytable_css_1ptdxmwejc6ery1m8v3o { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_z2esqpsw728nw8e3g9n1, .table th.tinytable_css_z2esqpsw728nw8e3g9n1 { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_y2qxw7f1of8z6nwtfca0, .table th.tinytable_css_y2qxw7f1of8z6nwtfca0 { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_x3moftfndwp8pyleps4o, .table th.tinytable_css_x3moftfndwp8pyleps4o { text-align: left; }\n      .table td.tinytable_css_ebceetzjboq80uzxvalg, .table th.tinytable_css_ebceetzjboq80uzxvalg { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_xdck5ncwmuzg9rgea53b\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Cobb-Douglas (log-log)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>p-values are '+' p < 0.1, '\\*' p < 0.05, '\\*\\*' p < 0.01, '\\*\\*\\*' p < 0.001. Standard errors are reported in parentheses</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">Dep. var.</td>\n                  <td data-row=\"1\" data-col=\"1\">log(Rice output, kg)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">BIMAS [YES]</td>\n                  <td data-row=\"2\" data-col=\"1\">0.118 (0.041)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">BIMAS [MIXED]</td>\n                  <td data-row=\"3\" data-col=\"1\">-0.142 (0.033)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">log(Size, HA)</td>\n                  <td data-row=\"4\" data-col=\"1\">0.555 (0.027)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"0\">Family labor, h</td>\n                  <td data-row=\"5\" data-col=\"1\">0.042 (0.015)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"0\">Hired labor, h</td>\n                  <td data-row=\"6\" data-col=\"1\">0.035 (0.011)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"0\">Urea, kg</td>\n                  <td data-row=\"7\" data-col=\"1\">0.247 (0.028)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"0\">Phosphate, kg</td>\n                  <td data-row=\"8\" data-col=\"1\">0.133 (0.021)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"0\">(Intercept)</td>\n                  <td data-row=\"9\" data-col=\"1\">5.721 (0.150)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"0\">Num.Obs.</td>\n                  <td data-row=\"10\" data-col=\"1\">883</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"0\">R2</td>\n                  <td data-row=\"11\" data-col=\"1\">0.878</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"0\">R2 Adj.</td>\n                  <td data-row=\"12\" data-col=\"1\">0.877</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n:::\n:::\n\n## 6. Interpretation with log (2) {.smaller}\n\n::: columns\n::: {.column width=\"45%\"}\n`log(size)` the total area cultivated with rice, measured in hectares;\n\n-   `log-log` transformation.\n\n-   Increase of the farm size by 1% is associated with the 0.56% increase in the rice output, given that all other factors remain fixed.\n\n-   These results are significant at the 5% significance level.\n:::\n\n::: {.column width=\"55%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_wvd2abemaryuemnakqnr(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_wvd2abemaryuemnakqnr\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_wvd2abemaryuemnakqnr(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_wvd2abemaryuemnakqnr\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '12', j: 1 },  ], css_id: 'tinytable_css_zvxcpk7z3ixvd4nmgphj',}, \n          { positions: [ { i: '10', j: 1 },  ], css_id: 'tinytable_css_g1x3os6w3890a14fk8nz',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 },  ], css_id: 'tinytable_css_xymxhu5r4ncr8kgff31p',}, \n          { positions: [ { i: '0', j: 1 },  ], css_id: 'tinytable_css_i2b9dwrm9djtoeyi77iu',}, \n          { positions: [ { i: '12', j: 0 },  ], css_id: 'tinytable_css_8wh3nog3llefgf2idh1n',}, \n          { positions: [ { i: '10', j: 0 },  ], css_id: 'tinytable_css_kus8mmaxyz60pkiyzja5',}, \n          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 }, { i: '3', j: 0 }, { i: '4', j: 0 }, { i: '5', j: 0 }, { i: '6', j: 0 }, { i: '7', j: 0 }, { i: '8', j: 0 }, { i: '9', j: 0 }, { i: '11', j: 0 },  ], css_id: 'tinytable_css_kl7asi0whi5306a6293v',}, \n          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_ru84dot2geslez9nzo03',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_wvd2abemaryuemnakqnr(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_zvxcpk7z3ixvd4nmgphj, .table th.tinytable_css_zvxcpk7z3ixvd4nmgphj { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_g1x3os6w3890a14fk8nz, .table th.tinytable_css_g1x3os6w3890a14fk8nz { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_xymxhu5r4ncr8kgff31p, .table th.tinytable_css_xymxhu5r4ncr8kgff31p { text-align: center; }\n      .table td.tinytable_css_i2b9dwrm9djtoeyi77iu, .table th.tinytable_css_i2b9dwrm9djtoeyi77iu { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_8wh3nog3llefgf2idh1n, .table th.tinytable_css_8wh3nog3llefgf2idh1n { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_kus8mmaxyz60pkiyzja5, .table th.tinytable_css_kus8mmaxyz60pkiyzja5 { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_kl7asi0whi5306a6293v, .table th.tinytable_css_kl7asi0whi5306a6293v { text-align: left; }\n      .table td.tinytable_css_ru84dot2geslez9nzo03, .table th.tinytable_css_ru84dot2geslez9nzo03 { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_wvd2abemaryuemnakqnr\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Cobb-Douglas (log-log)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>p-values are '+' p < 0.1, '\\*' p < 0.05, '\\*\\*' p < 0.01, '\\*\\*\\*' p < 0.001. Standard errors are reported in parentheses</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">Dep. var.</td>\n                  <td data-row=\"1\" data-col=\"1\">log(Rice output, kg)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">BIMAS [YES]</td>\n                  <td data-row=\"2\" data-col=\"1\">0.118 (0.041)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">BIMAS [MIXED]</td>\n                  <td data-row=\"3\" data-col=\"1\">-0.142 (0.033)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">log(Size, HA)</td>\n                  <td data-row=\"4\" data-col=\"1\">0.555 (0.027)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"0\">Family labor, h</td>\n                  <td data-row=\"5\" data-col=\"1\">0.042 (0.015)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"0\">Hired labor, h</td>\n                  <td data-row=\"6\" data-col=\"1\">0.035 (0.011)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"0\">Urea, kg</td>\n                  <td data-row=\"7\" data-col=\"1\">0.247 (0.028)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"0\">Phosphate, kg</td>\n                  <td data-row=\"8\" data-col=\"1\">0.133 (0.021)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"0\">(Intercept)</td>\n                  <td data-row=\"9\" data-col=\"1\">5.721 (0.150)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"0\">Num.Obs.</td>\n                  <td data-row=\"10\" data-col=\"1\">883</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"0\">R2</td>\n                  <td data-row=\"11\" data-col=\"1\">0.878</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"0\">R2 Adj.</td>\n                  <td data-row=\"12\" data-col=\"1\">0.877</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n:::\n:::\n\n## 6. Interpretation with log (3) {.smaller}\n\n::: columns\n::: {.column width=\"45%\"}\n-   Participating in the BIMAS on a MIXED basis reduces the gross output of rice by $100 \\cdot e^{-0.142}-1 = - 100 \\cdot 0.132 = -13.2$ % (reduces by 13.2%) compared to non-participation given that all other factors remain fixed. The effect is significant at the 5% level of significance.\n\n-   Participating in the BIMAS on a full basis (yes) basis increases the gross output of rice by: $100 \\cdot e^{0.118}-1 = 100 \\cdot 0.125 = 12.5$ % (increases by 12.2%) compared to non-participation given that all other factors remain fixed. The effect is significant at the 5% level of significance.\n:::\n\n::: {.column width=\"55%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_du7bffi3g2x0q169ytxn(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_du7bffi3g2x0q169ytxn\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_du7bffi3g2x0q169ytxn(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_du7bffi3g2x0q169ytxn\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '12', j: 1 },  ], css_id: 'tinytable_css_agpa98726pfyvudajndq',}, \n          { positions: [ { i: '10', j: 1 },  ], css_id: 'tinytable_css_mj2bg04vtnnvr7g1ad68',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 },  ], css_id: 'tinytable_css_15j9orx102en5eo0zq4l',}, \n          { positions: [ { i: '0', j: 1 },  ], css_id: 'tinytable_css_fhu01y8mmvuqk2vrlfl7',}, \n          { positions: [ { i: '12', j: 0 },  ], css_id: 'tinytable_css_4yl60j4eqyyh6i31n9z1',}, \n          { positions: [ { i: '10', j: 0 },  ], css_id: 'tinytable_css_1oxix0ghubfrsy6mfmoz',}, \n          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 }, { i: '3', j: 0 }, { i: '4', j: 0 }, { i: '5', j: 0 }, { i: '6', j: 0 }, { i: '7', j: 0 }, { i: '8', j: 0 }, { i: '9', j: 0 }, { i: '11', j: 0 },  ], css_id: 'tinytable_css_2hi9eoclybddh3eq0om2',}, \n          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_2yp5ufq6vngnkkwzhj9p',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_du7bffi3g2x0q169ytxn(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_agpa98726pfyvudajndq, .table th.tinytable_css_agpa98726pfyvudajndq { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_mj2bg04vtnnvr7g1ad68, .table th.tinytable_css_mj2bg04vtnnvr7g1ad68 { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_15j9orx102en5eo0zq4l, .table th.tinytable_css_15j9orx102en5eo0zq4l { text-align: center; }\n      .table td.tinytable_css_fhu01y8mmvuqk2vrlfl7, .table th.tinytable_css_fhu01y8mmvuqk2vrlfl7 { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_4yl60j4eqyyh6i31n9z1, .table th.tinytable_css_4yl60j4eqyyh6i31n9z1 { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_1oxix0ghubfrsy6mfmoz, .table th.tinytable_css_1oxix0ghubfrsy6mfmoz { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_2hi9eoclybddh3eq0om2, .table th.tinytable_css_2hi9eoclybddh3eq0om2 { text-align: left; }\n      .table td.tinytable_css_2yp5ufq6vngnkkwzhj9p, .table th.tinytable_css_2yp5ufq6vngnkkwzhj9p { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_du7bffi3g2x0q169ytxn\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Cobb-Douglas (log-log)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>p-values are '+' p < 0.1, '\\*' p < 0.05, '\\*\\*' p < 0.01, '\\*\\*\\*' p < 0.001. Standard errors are reported in parentheses</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">Dep. var.</td>\n                  <td data-row=\"1\" data-col=\"1\">log(Rice output, kg)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">BIMAS [YES]</td>\n                  <td data-row=\"2\" data-col=\"1\">0.118 (0.041)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">BIMAS [MIXED]</td>\n                  <td data-row=\"3\" data-col=\"1\">-0.142 (0.033)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">log(Size, HA)</td>\n                  <td data-row=\"4\" data-col=\"1\">0.555 (0.027)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"0\">Family labor, h</td>\n                  <td data-row=\"5\" data-col=\"1\">0.042 (0.015)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"0\">Hired labor, h</td>\n                  <td data-row=\"6\" data-col=\"1\">0.035 (0.011)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"0\">Urea, kg</td>\n                  <td data-row=\"7\" data-col=\"1\">0.247 (0.028)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"0\">Phosphate, kg</td>\n                  <td data-row=\"8\" data-col=\"1\">0.133 (0.021)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"0\">(Intercept)</td>\n                  <td data-row=\"9\" data-col=\"1\">5.721 (0.150)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"0\">Num.Obs.</td>\n                  <td data-row=\"10\" data-col=\"1\">883</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"0\">R2</td>\n                  <td data-row=\"11\" data-col=\"1\">0.878</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"0\">R2 Adj.</td>\n                  <td data-row=\"12\" data-col=\"1\">0.877</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n:::\n:::\n\n## 6. Interpretation with log (4) DIY {.smaller}\n\n::: columns\n::: {.column width=\"45%\"}\n-   `urea` or `phosphate` application in kilogram;\n-   `hiredlabor` or `famlabor` in hours\n:::\n\n::: {.column width=\"55%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_j69zrs7z8q71wszegqxa(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_j69zrs7z8q71wszegqxa\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_j69zrs7z8q71wszegqxa(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_j69zrs7z8q71wszegqxa\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '12', j: 1 },  ], css_id: 'tinytable_css_1057c5tdki5z00h4o3xy',}, \n          { positions: [ { i: '10', j: 1 },  ], css_id: 'tinytable_css_wo8cfkfj7wi0q45eguh2',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 },  ], css_id: 'tinytable_css_kvsoppcqjzbp5n7cu52g',}, \n          { positions: [ { i: '0', j: 1 },  ], css_id: 'tinytable_css_5eqk373awfslssgssf40',}, \n          { positions: [ { i: '12', j: 0 },  ], css_id: 'tinytable_css_zmpcmshuy0mypm424oye',}, \n          { positions: [ { i: '10', j: 0 },  ], css_id: 'tinytable_css_af6ncdlmjz7ui72pxuqu',}, \n          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 }, { i: '3', j: 0 }, { i: '4', j: 0 }, { i: '5', j: 0 }, { i: '6', j: 0 }, { i: '7', j: 0 }, { i: '8', j: 0 }, { i: '9', j: 0 }, { i: '11', j: 0 },  ], css_id: 'tinytable_css_5qlaajuba7vg76b6ev82',}, \n          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_q5y6jh6j3f66zrow31hm',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_j69zrs7z8q71wszegqxa(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_1057c5tdki5z00h4o3xy, .table th.tinytable_css_1057c5tdki5z00h4o3xy { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_wo8cfkfj7wi0q45eguh2, .table th.tinytable_css_wo8cfkfj7wi0q45eguh2 { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_kvsoppcqjzbp5n7cu52g, .table th.tinytable_css_kvsoppcqjzbp5n7cu52g { text-align: center; }\n      .table td.tinytable_css_5eqk373awfslssgssf40, .table th.tinytable_css_5eqk373awfslssgssf40 { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_zmpcmshuy0mypm424oye, .table th.tinytable_css_zmpcmshuy0mypm424oye { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_af6ncdlmjz7ui72pxuqu, .table th.tinytable_css_af6ncdlmjz7ui72pxuqu { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_5qlaajuba7vg76b6ev82, .table th.tinytable_css_5qlaajuba7vg76b6ev82 { text-align: left; }\n      .table td.tinytable_css_q5y6jh6j3f66zrow31hm, .table th.tinytable_css_q5y6jh6j3f66zrow31hm { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_j69zrs7z8q71wszegqxa\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Cobb-Douglas (log-log)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>p-values are '+' p < 0.1, '\\*' p < 0.05, '\\*\\*' p < 0.01, '\\*\\*\\*' p < 0.001. Standard errors are reported in parentheses</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">Dep. var.</td>\n                  <td data-row=\"1\" data-col=\"1\">log(Rice output, kg)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">BIMAS [YES]</td>\n                  <td data-row=\"2\" data-col=\"1\">0.118 (0.041)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">BIMAS [MIXED]</td>\n                  <td data-row=\"3\" data-col=\"1\">-0.142 (0.033)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">log(Size, HA)</td>\n                  <td data-row=\"4\" data-col=\"1\">0.555 (0.027)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"0\">Family labor, h</td>\n                  <td data-row=\"5\" data-col=\"1\">0.042 (0.015)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"0\">Hired labor, h</td>\n                  <td data-row=\"6\" data-col=\"1\">0.035 (0.011)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"0\">Urea, kg</td>\n                  <td data-row=\"7\" data-col=\"1\">0.247 (0.028)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"0\">Phosphate, kg</td>\n                  <td data-row=\"8\" data-col=\"1\">0.133 (0.021)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"0\">(Intercept)</td>\n                  <td data-row=\"9\" data-col=\"1\">5.721 (0.150)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"0\">Num.Obs.</td>\n                  <td data-row=\"10\" data-col=\"1\">883</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"0\">R2</td>\n                  <td data-row=\"11\" data-col=\"1\">0.878</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"0\">R2 Adj.</td>\n                  <td data-row=\"12\" data-col=\"1\">0.877</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n:::\n:::\n\n## 8. Conclusions {.smaller}\n\n::: columns\n::: {.column width=\"25%\"}\nWhat is the causal effect of BIMAS program on the gross output of rice?\n\nWhat is the goodness of fit of the model?\n\nEQ: **Which model explains the relationship between inputs and outputs more accurately (with less bias)?**\n\nEQ: **Which model has a higher explanatory power?**\n:::\n\n::: {.column width=\"75%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_ybqpb2j494o36bwa2nsd(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_ybqpb2j494o36bwa2nsd\");\n          var cell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function spanCell_ybqpb2j494o36bwa2nsd(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_ybqpb2j494o36bwa2nsd\");\n        const targetCell = table.querySelector(`[data-row=\"${i}\"][data-col=\"${j}\"]`);\n        if (!targetCell) {\n          console.warn(`Cell at (${i}, ${j}) not found.`);\n        }\n\n        // Get all cells that need to be removed\n        const cellsToRemove = [];\n        for (let r = 0; r < rowspan; r++) {\n          for (let c = 0; c < colspan; c++) {\n            if (r === 0 && c === 0) continue; // Skip the target cell\n            const cell = table.querySelector(`[data-row=\"${i + r}\"][data-col=\"${j + c}\"]`);\n            if (cell) {\n              cellsToRemove.push(cell);\n            }\n          }\n        }\n\n        // Remove all cells\n        cellsToRemove.forEach(cell => cell.remove());\n\n        // Set rowspan and colspan of the target cell if it exists\n        if (targetCell) {\n          targetCell.rowSpan = rowspan;\n          targetCell.colSpan = colspan;\n        }\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '13', j: 1 }, { i: '13', j: 2 },  ], css_id: 'tinytable_css_n7pypp1cba08dt99hx67',}, \n          { positions: [ { i: '11', j: 1 }, { i: '11', j: 2 },  ], css_id: 'tinytable_css_szfijsn0iiyblrgudu43',}, \n          { positions: [ { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '10', j: 2 }, { i: '12', j: 1 }, { i: '12', j: 2 }, { i: '1', j: 1 }, { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 },  ], css_id: 'tinytable_css_jr08mnfjgfq401wsp06k',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 },  ], css_id: 'tinytable_css_5707mu0hvprr6cwlu0is',}, \n          { positions: [ { i: '13', j: 0 },  ], css_id: 'tinytable_css_c50pm12rl97c1c1279g5',}, \n          { positions: [ { i: '11', j: 0 },  ], css_id: 'tinytable_css_di5090elcjjxj7l3dkek',}, \n          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 }, { i: '3', j: 0 }, { i: '4', j: 0 }, { i: '5', j: 0 }, { i: '6', j: 0 }, { i: '7', j: 0 }, { i: '8', j: 0 }, { i: '9', j: 0 }, { i: '10', j: 0 }, { i: '12', j: 0 },  ], css_id: 'tinytable_css_jtvaf00ov07htah8oeth',}, \n          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_dvsgaa1d4jntpa4nrccm',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_ybqpb2j494o36bwa2nsd(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_n7pypp1cba08dt99hx67, .table th.tinytable_css_n7pypp1cba08dt99hx67 { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_szfijsn0iiyblrgudu43, .table th.tinytable_css_szfijsn0iiyblrgudu43 { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_jr08mnfjgfq401wsp06k, .table th.tinytable_css_jr08mnfjgfq401wsp06k { text-align: center; }\n      .table td.tinytable_css_5707mu0hvprr6cwlu0is, .table th.tinytable_css_5707mu0hvprr6cwlu0is { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_c50pm12rl97c1c1279g5, .table th.tinytable_css_c50pm12rl97c1c1279g5 { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_di5090elcjjxj7l3dkek, .table th.tinytable_css_di5090elcjjxj7l3dkek { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_jtvaf00ov07htah8oeth, .table th.tinytable_css_jtvaf00ov07htah8oeth { text-align: left; }\n      .table td.tinytable_css_dvsgaa1d4jntpa4nrccm, .table th.tinytable_css_dvsgaa1d4jntpa4nrccm { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_ybqpb2j494o36bwa2nsd\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"0\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Linear (level-level)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Cobb-Douglas(log-log)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='3'>p-values are '+' p < 0.1, '\\*' p < 0.05, '\\*\\*' p < 0.01, '\\*\\*\\*' p < 0.001. Standard errors are reported in parentheses</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"0\">Dep. var.</td>\n                  <td data-row=\"1\" data-col=\"1\">Rice output, kg</td>\n                  <td data-row=\"1\" data-col=\"2\">log(Rice output, kg)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"0\">BIMAS [YES]</td>\n                  <td data-row=\"2\" data-col=\"1\">157.873 (83.126)+</td>\n                  <td data-row=\"2\" data-col=\"2\">0.118 (0.041)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"0\">BIMAS [MIXED]</td>\n                  <td data-row=\"3\" data-col=\"1\">-262.076 (68.135)***</td>\n                  <td data-row=\"3\" data-col=\"2\">-0.142 (0.033)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"0\">Size, HA</td>\n                  <td data-row=\"4\" data-col=\"1\">1824.022 (138.407)***</td>\n                  <td data-row=\"4\" data-col=\"2\"></td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"0\">log(Size, HA)</td>\n                  <td data-row=\"5\" data-col=\"1\"></td>\n                  <td data-row=\"5\" data-col=\"2\">0.555 (0.027)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"0\">Family labor, h</td>\n                  <td data-row=\"6\" data-col=\"1\">0.789 (0.186)***</td>\n                  <td data-row=\"6\" data-col=\"2\">0.042 (0.015)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"0\">Hired labor, h</td>\n                  <td data-row=\"7\" data-col=\"1\">1.037 (0.131)***</td>\n                  <td data-row=\"7\" data-col=\"2\">0.035 (0.011)**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"0\">Urea, kg</td>\n                  <td data-row=\"8\" data-col=\"1\">-0.034 (0.392)</td>\n                  <td data-row=\"8\" data-col=\"2\">0.247 (0.028)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"0\">Phosphate, kg</td>\n                  <td data-row=\"9\" data-col=\"1\">11.086 (0.744)***</td>\n                  <td data-row=\"9\" data-col=\"2\">0.133 (0.021)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"0\">(Intercept)</td>\n                  <td data-row=\"10\" data-col=\"1\">-107.915 (38.362)**</td>\n                  <td data-row=\"10\" data-col=\"2\">5.721 (0.150)***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"0\">Num.Obs.</td>\n                  <td data-row=\"11\" data-col=\"1\">883</td>\n                  <td data-row=\"11\" data-col=\"2\">883</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"0\">R2</td>\n                  <td data-row=\"12\" data-col=\"1\">0.871</td>\n                  <td data-row=\"12\" data-col=\"2\">0.878</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"0\">R2 Adj.</td>\n                  <td data-row=\"13\" data-col=\"1\">0.870</td>\n                  <td data-row=\"13\" data-col=\"2\">0.877</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n:::\n:::\n\n\n# Example 3. @Duflo2008 How High Are Rates of Return to Fertilizer? Evidence from Field Experiments in Kenya\n\n---\neditor: source\nformat: \n  revealjs:\n    preview-links: true\neditor_options: \n  chunk_output_type: console\n---\n\n## Objective {.smaller}\n\nIn [@Duflo2008] authors are trying to estimate the effect of fertilizers application on farms profit.\n\nThey employ and randomized controlled trial experiment randomly selecting farmers between children's parents in certain schools.\n\nOn each farm, they demarcate 3 experimental fields and train farmers how to apply certain quantities of fertilizers on these fields. They also supervised the farmers over the growing seasons accurately collected the harvest and measured the outcome each time.\n\nIn each trial, random plots (out of the demarcated ones) were selected on each farm for applying different levels of fertilizers.\n\nThe authors measured:\n\n-   returns as \\[output value of (treatment - control) - inputs cost\\] / \\[inputs cost\\]\n-   yields change (treatment - control) / (control) \\* 100\n\n## Results {.smaller}\n\n![](img/duflo2008_T1.png)\n\n::: columns\n::: {.column width=\"50%\"}\nColumn (1) reports the mean in returns and yields between control and treatment fields for different rates of fertilizer application overall growing seasons.\n:::\n\n::: {.column width=\"50%\"}\n-   What yield change is associated with different levels of fertilizer application?\n\n-   Can we conclude that fertilizer application improves yields/returns on average in the population?\n\n-   What rates of fertilizer application improve yields/returns on average in the population?\n:::\n:::\n\n## Is the ceteris paribus ensured in this RCT?\n\nAuthors were criticized if the ceteris paribus holds in their experiment\n\n-   specifically concerning the monetary return levels.\n\n-   monetary outcomes often depend on many observed and unobserved factors, therefore, they are often seen as \"endogenous\" in econometrics.\n\n    -   What other factors can affect the return?\n\n    -   How can we ensure that other factors do not affect the return?\n\n## Authors solution is the regression analysis\n\n::: fragment\n$$\n\\begin{aligned}\n\\operatorname{Return} &= \\beta_0 +\n\\beta_1 \\operatorname{Farm size} + \n\\beta_2 \\operatorname{Education} + \n\\beta_3 \\operatorname{Income} \\\\ & + \n\\beta_4 \\operatorname{Experience in fertilizer use} + \\cdots \\\\ & + \n\\beta_k \\operatorname{Other factors} + \\epsilon\n\\end{aligned}\n$$\n:::\n\nIf other factors affect the return,\n\n-   What signs/values coefficients $\\beta_\\cdot$ should have?\n\n-   Formulate ex-ante hypotheses about the expected signs of the coefficients.\n\n## Checks and balances (1)\n\n![](img/duflo2008_T2.png)\n\nNote: p-values are '\\*' p \\< 0.1, '\\*\\*' p \\< 0.05, '\\*\\*\\*' p \\< 0.01. Standard errors are reported in parentheses.\n\n## Checks and balances (2)\n\n::: columns\n::: {.column width=\"75%\"}\n![](img/duflo2008_T2.png)\n\nNote: p-values are '\\*' p \\< 0.1, '\\*\\*' p \\< 0.05, '\\*\\*\\*' p \\< 0.01. Standard errors are reported in parentheses.\n\nThe dependent variable in all regressions is Return %. Only sub-samples are different between the columns.\n:::\n\n::: {.column width=\"25%\"}\n-   What effect does education or other factors have on the return?\n\n-   Has the RCT experiment ensured the ceteris paribus?\n\n-   What about the GOF? How well do regressions explain variance in return? Is it enough to make any (previous) conclusions?\n:::\n:::\n\n\n# Regression in Excel\n\nYou can use Excel to perform a regression analysis. There are many tutorials online.\n\nSee for example: [https://youtu.be/9wX1a1J4WOI](https://youtu.be/9wX1a1J4WOI?si=9S_Sa46Urfk_QBEB)\n\n# References\n",
    "supporting": [
      "mk68-07-slides_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}