---
title: "Week 06. Recap. Simple Linear Regression. Multiple Regression. Bias. Regression assumptions. Linearity."
editor: source
format: 
  revealjs:
    preview-links: true
editor_options: 
  chunk_output_type: console
---

{{< include t-test-recap.qmd >}}

{{< include very-simple-regression.qmd >}}

# Multiple regression

-   Watch: Selection Bias: <https://youtu.be/6YrIDhaUQOE>

-   Readings for your reference:

    -   Chapter 2 in @Angrist2014
    -   Chapter 3 in @Angrist2009

{{< include MLR.qmd >}}

# Bias and Efficiency

{{< include mk68-07-Bias-Efficiency.qmd >}}

# Assumptions of the MLR {.smaller}

> exist to ensure that linear regression estimates are unbiased and efficient!

::: {.callout-important appearance="minimal"}
### OLS is unbiased. Assumptions 1 to 4 are satisfied:

1.  Linearity
2.  Random Sampling
3.  No Collinearity
4.  No Endogeneity
:::

::: {.callout-warning appearance="minimal"}
### OLS is unbiased and efficient. Best Linear Unbiased Estimator (BLUE). Assumptions 1 to 5 are satisfied

5.  Homoscedasticity (No Autocorrelation)
:::

::: {.callout-caution appearance="minimal"}
### OLS is a Classical linear model (CLM). Assumptions 1 to 6 are satisfied

6.  Error Terms Normality
:::

# Assumption 1. Linearity

{{< include linearity-simple.qmd >}}

# Takeaways checklist

## Key concepts covered in the lecture {.smaller}

::: columns
::: {.column width="50%"}
Simple linear regression:

-   Regressor and regressand;
-   Fitted values and residuals;
-   OLS method;
-   Estimated coefficients;
-   Interpretation of the slope and the intercept.
-   HT about the regression coefficients.

Ceteris Paribus

-   Establishing Ceteris Paribus without an RCT.
-   Multiple Linear Regression that controls for other things.
:::

::: {.column width="50%"}
Multiple linear regression

-   Coefficients, HT and interpretation.
-   Goodness of fit.
-   Causal meaning.
-   Observed included, not included and unobserved factors.
-   Interpreting coefficients of the MLR.

Assumptions of the regression analysis.

-   Bias and unbiased estimates.
-   Role of assumptions in the bias of the estimates.

Linearity assumption

-   Detection.
-   Implications or why the linearity assumption is important.
-   How to correct the non-linearity (linear transformation).
:::
:::

# Self-study: Cradle of the Regression Analysis

-   The term "regression" was coined by Sir Francis Galton, Charles Darwin's half-cousin, in 1886

    -   he was gripped by Darwin's masterpiece, The Origin of Species.

    -   he used "Regression" to prove his points of Eugenics...

> Statistics has some dark history...

> Paper: Francis Galton, "Regression towards Mediocrity in Hereditary Stature," Journal of the Anthropological Institute of Great Britain and Ireland, vol. 15, 1886, pages 246--263

## Galton's introduction of regression

-   Galton discovered that the average heights of fathers and sons are linked by a regression equation.

-   the average height of sons is a weighted average of their fathers' height and the average height in the population from which the fathers and sons were sampled.

## First application in causality analysis

-   pioneered by George Udny Yule in "An Investigation into the Causes of Changes in Pauperism in England, Chiefly during the Last Two Intercensal Decades," Journal of the Royal Statistical Society, vol. 62, no. 2, June 1899, pages 249--295.

-   Student of statistician Karl Pearson (Pearson's correlation ...) and Galton's protege.

Yule realized that Galton's regression method could be extended to include many variables (multiple regression).

## George Udny Yule {.smaller}

In an 1899 MLR was used to link the administration of the English Poor Laws in different counties to the likelihood county residents were poor, while controlling for population growth and the age distribution in the county.

-   The poor laws provided subsistence for the indigent, usually by offering shelter and employment in institutions called workhouses.

-   Yule was particularly interested in whether the practice of outdoor relief, which provided income support for poor people without requiring them to move to a workhouse, increased poverty rates by making pauperism less onerous.

-   This is a well-defined causal question much like those that occupy social scientists today.

## The past of statistics

Statistics has a dark past.

-   It was used and developed in the disposal of really terrible things like Eugenics.

-   But the world was terrible then.

Nowadays, same statistical methods are fundamental for revealing causal effects as 100 years ago.

-   Yet we apply it for some different causes.

# References
