---
title: "Week 04. Cause and Effect in the RCT. Hypothesis testing. T-tests. Exmples"
editor: source
format: 
  revealjs:
    preview-links: true
    incremental: false
editor_options: 
  chunk_output_type: console
---

```{r}
#| include: false
# source(here::here("materials", "00-setup.R"), local = TRUE)
knitr::opts_chunk$set(fig.width = 8)
knitr::opts_chunk$set(fig.height = 4.5)
```

{{< include ceteris-paribus.qmd >}}

{{< include hypothesis-testing.qmd >}}

{{< include t-test.qmd >}}

{{< include deworming.qmd >}}


# Homework

1.  [Econometrics: The Path from Cause to Effect](https://youtu.be/WwW8y5dZs80)
2.  [Ceteris Paribus: Public vs. Private University](https://youtu.be/iPBV3BlV7jk)
3.  [Selection Bias: Will You Make More Going to a Private University?](https://youtu.be/6YrIDhaUQOE)
4.  [Randomized Trials: The Ideal Weapon](https://youtu.be/eGRd8jBdNYg)



# Takeaways checklist

## Homework

Make the topic-specific homework.

Answer sample exam questions.

Same readings:

-   [@Kuchenbecker2017] **before the week 4**;
-   [@Gertler2004] another example of the statistics application;
-   [@Miguel2004] Deworming effect on children health;
-   [@Hamory2021] Long-term economic effect of de-worming;
-   [@Carter2017] Effect of electronics on students performance.

## Key concepts covered in the lecture {.smaller}

::: columns
::: {.column width="50%"}
RCT:

-   Causal meaning of the averages;
-   Random sample variation;
-   Need of the statistical hypothesis testing;
:::

::: {.column width="50%"}
Hypothesis testing:

-   Type I and Type II errors;
-   Significance level;
-   Null and Alternative Hypotheses;
-   What is the probability value (p-value)?
-   What do false-negative/false-positive mean?

T-test:

-   One-sided/Two-sided.
-   Critical values of the t-distributions
-   t statistics
-   Mechanics of the test statistics calculaiton.
:::
:::

# References
